### ISSUE TITLE
GUI Followers [Forge/Fabric] - Several feature requests

### ISSUE THREAD

**Issue by Abbanon** [ricksouth/serilum-mc-mods#1016]
## **Information**
Mod name: GUI Followers

## **Feature descriptions**
- Ability to toggle the follower list on/off via keybind
- Font drop shadows (for visual parity with other GUI/HUD text elements)
- Horizontal (X) offset coordinates to match the existing vertical (Y) offset coordinates
- Optional feature to make a follower's line transition between colours based on health percentage (100%-75%-50%-25%)
(with the ability to customize each colour's RGB values + what health percentage each colour occurs at)

**Comment by ainlzj** [comment]
I have another opinion, surround the dog's head with a simple inventory block and display the health value next to it ( GUI ❤X20 distance: number) This is more concise

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
