### ISSUE TITLE
Add relative saveinventory and loadinventory

### ISSUE THREAD

**Issue by Tomergngn** [ricksouth/serilum-mc-mods#1041]
## **Information**
Mod name: Save and Load Inventories

## **Feature description**
I've been working on a datapack for a server with my friends, and I wanted to save everyone's inventory who died, in their own unique name. I coded the entire "check who died only once" thing, and just plugged in the saveinventory command, and saw that "saveinventory @s" and "loadinventory @s" doesn't work.. It would be so good for servers if you could have that! I don't think it's that hard to implement either. just have specific inputs that trigger those custom events:

"saveinventory @s" - get the player's name, and save the inventory on his name
"loadinventory @s" - search for an inventory with the player's name

it would be so much easier for me and for everyone (I think).
Thanks ahead, Tomer

**Comment by MattB70** [comment]
This would be really nice!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
