### ISSUE TITLE
Your Items Are Safe (Fabric) -- X/Y/Z position in SuccessMessage

### ISSUE THREAD

**Issue by SushiKishi** [ricksouth/serilum-mc-mods#1070]
## **Information**
Mod name: Your Items Are Safe (Fabric)

## **Feature description**
I'd like to be able to use something like the %planksNeeded% attribute in the success line to know where your stuff will be. by using %posX% %posY% %posZ%. This is mostly for my mom, the minimap mod I think causes a bit of lag for her, and it's a bit too much gamer information for her, so she'd like to get rid of it. That's really the only way i've found to be able to find her position when she gets hopelessly lost though lol

I think I maybe even know how to do it! I followed the tutorial for creating a Fabric Minecraft mod, and the tutorial mod works fine. So I was hoping to drop in the Your Items Are Safe code in and try to test out some code myself, but...no dice. I can't even get it to build to a fabric-loom error.

What I was going to do was this:

DeathEvent.Java, line 215:
```
Util.successMessage(player, deathpos.getX(), deathpos.getY()+1, deathpos.getZ());
//*That +1 might throw something off in *this* situation, but again, I can't test to find out.
//I figured it was just there to round the Y coordinate properly because it gets floor()'ed by Minecraft or something.
```

Util.java, line 110 -- change the successMessage function to this:

```
public static void successMessage(Player player, int posX, int posY, int posZ) {
		if (ConfigHandler.sendMessageOnCreationSuccess.getValue()) {

			String successstring = ConfigHandler.creationSuccessMessage.getValue();
			failurestring = failurestring.replaceAll("%posX%", posX + "").replaceAll("%posY%", posY + "").replaceAll("%posY%", posZ + "");

			StringFunctions.sendMessage(player, successstring, ChatFormatting.DARK_GREEN);
		}	
```

I'd have done a pull request, but I didn't want to do that for something I can't guarantee even builds much less works properly.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!

**Comment by ricksouth** [comment]
Thanks again! This has been added in version 4.0 of Your Items Are Safe.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
