### ISSUE TITLE
Server Tick Performance issues with Random Village Names (Forge)

### ISSUE THREAD

**Issue by MaxWasUnavailable** [ricksouth/serilum-mc-mods#1077]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.20
Environment: Singleplayer & Multiplayer

Mod name: Random Village Names (Forge)
Mod version: randomvillagenames_1.18.2-1.6.jar

## **Description**
Profiling the game with Spark shows RandomVillageNames' find structure / place sign methods take up ~30% of the server's tick processing time.

**Comment by Shadowex3** [comment]
I think this might be what I'm experiencing as well. I'm having _extreme_ lag in a singleplayer world despite >100fps and a fairly powerful computer. Profiling with spark got the below, it appears `com.natamus.collective.functions.BlockPosFunctions.getNearbyStructure()` is shnorfing huge amounts of server time. Ditching Random Village Names led to an astronomical improvement in performance.

![image](https://user-images.githubusercontent.com/57022604/183988911-e252b32b-df99-4d9e-b93e-72d33fde74da.png)

**Comment by Proxwian** [comment]
Same problem here, so much tick perfomance affecting

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Random Village Names. It took a complete rewrite to fix the issue, but it should be a lot more efficient. I appreciate the patience and the detailed information. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
