### ISSUE TITLE
Hide-Hands mod question

### ISSUE THREAD

**Issue by JustDemonic** [ricksouth/serilum-mc-mods#1107]
## **a question / feature idea for the Hide-Hands mod.**
Minecraft version: 1.12.2
Modloader: Forge
Environment: Singleplayer
Mod Name: Hide Hands (Forge)
Mod version: 1.3

**I'm confused on how to configure the mod. i have a first person render mod installed and to make it realistic, i want it so that the hands are hidden but when i have items on my hands, it will show the items but it hides everything instead. How do i configure it correctly?**

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
This has been implemented in version 3.0 of the mod. The hand will still be temporily shown when swung. The functionality can be turned on/off in the config. Thanks for the suggestion!

https://www.curseforge.com/minecraft/mc-mods/hide-hands/files
