### ISSUE TITLE
Mod Idea for Villagers

### ISSUE THREAD

**Issue by Seshua** [ricksouth/serilum-mc-mods#1112]
## **Information**
Mod name: Villagers Follow You

## **Feature description**
I know you already can get villagers where you want them in vanilla but..

I like the Idea of the mod [Villagers Follow Emeralds](https://www.curseforge.com/minecraft/mc-mods/villagers-follow-emeralds), but 

1) It seems a bit too easy,
2) The mod creator hasn't updated it since 1.16

Therefore I'm creating this post in the hopes that you'll take this task under your wing. I'm not saying you need to copy the mod, I mean if you want to that's fine. Maybe something like you right click a (Jobless) villager and a context menu comes up and gives the option to hire a villager, by hire I mean they will follow you until you right click them again. Maybe it can cost a random amount (configurable) of emeralds to hire them. I don't know, what ever you think would be balanced is fine by me. Anyway thank you for considering.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
