### ISSUE TITLE
Allow zero costs & costs by level

### ISSUE THREAD

**Issue by yuyaryshev** [ricksouth/serilum-mc-mods#1116]
In "Fixed Anvil Repair Cost"
Allow setting costs to zero please. 

In my modpack Stone age is much longer and repair taking exp is way too much.

Also if costs could be set with respect to age (stone, iron, diamond) that would be great,

**Comment by James103** [comment]
The next best thing, if zero cost is infeasible due to anvil limitations and a one level cost is too much, would be to require players to have at least one XP level to rename or repair items, but the XP level used to repair/rename is immediately refunded when the operation is complete.

**Comment by yuyaryshev** [comment]
Pull request: https://github.com/ricksouth/serilum-mc-mods/pull/1145
Hotfix binary build for 1.18.2: https://github.com/yuyaryshev/serilum-mc-mods/blob/yya_dont_merge_to_master/sources/Fixed%20Anvil%20Repair%20Cost/fixedanvilrepaircost_1.18.2-1.7yya.jar

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
