### ISSUE TITLE
Mod Idea: command to hide player name tags

### ISSUE THREAD

**Issue by captaintekton** [ricksouth/serilum-mc-mods#1125]
## **Information**
Mod name: 

## **Feature description**
A command to hide player name tags on servers to make PVP more fair, or just for cosmetic preference. It can be toggled by players to hide name tags from their perspective, or it could be toggled by server ops to hide it from all players. 

something like:
/nametags (false/true)
or
/servernametags (false/true)

It could probably be derived from the nametag hiding feature enabled when crouching, at least for the server-wide part, I don't know about the client option though. That part is your expertise, I'm just making suggestions.
Thank you in advance if you choose to use this idea, and good luck!

**Comment by captaintekton** [comment]
I forgot to suggest a name
It could be something like:
"hide nametag command"
"PVP friendly nametags"
"no nametags"
"nametag slayer"
or whatever you think would fit

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
