### ISSUE TITLE
Compact Help /help command doesn't show anything

### ISSUE THREAD

**Issue by maddie-m** [ricksouth/serilum-mc-mods#1128]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Compact Help
Mod version: 1.3

## **Description**
Typing /help <command> does not show anything in the chat, whether it is a vanilla command or from a mod. For example, /help advancement does nothing, whereas without this mod it would show a description of the command. This doesn't seem like intended behaviour, at least it doesn't make much sense since typing /help prompts for a page number OR a command.

**Comment by DumbXBoxAcct** [comment]
I'm getting the same thing.  Removed all mods except Collective & CompactHelpCommand, removed my shader, resource packs & OptiFine, and sill got nothing when entering "Help Give" for instance, just blankness.  I'm running JE 1.19.2 with Forge 43.1.55, but this has been the case for all of the previous  Forge clients I've used since installing the mod.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.2 of Compact Help Command. Apologies it took so long for me to get to. The specific information will now also be shown beautified.

https://curseforge.com/minecraft/mc-mods/compact-help-command/files
