### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1146]
[Deleted]

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!
