### ISSUE TITLE
[Areas/Random Village Names] Village Sign will not accept new name.

### ISSUE THREAD

**Issue by SangurianSoul** [ricksouth/serilum-mc-mods#1147]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.34
Environment: Multiplayer

Mod name: Areas / Random Village Names
Mod version: 2.8 / 1.3

## **Description**
My village sign will not accept a new name. No matter what i change it to, the enter and leave message stays the same. If i break the sign, it almost instantly respawns with a new name. Placing another sign nearby does nothing. Replacing the sign with a new one the moment it breaks, also will do nothing. The area will remain unnamed despite writing on the sign otherwise. Breaking this new sign will allow a new one to auto-generate.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Random Village Names. You'll now be able to place your own sign in the village. Just make sure it's within a 15 block radius of the old sign and it'll be seen as the village area sign.

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
