### ISSUE TITLE
Demand stuck at 360

### ISSUE THREAD

**Issue by KojiroMC** [ricksouth/serilum-mc-mods#1153]
## **Information**
Mod name: Infinite Trading

## **Feature description**
Would there be a way to lock to demand at 0? Ive now reached a point where I've AFK'd at  the trading hall for 24 IRL hours and they still want 64 emeralds for a nametag

**Comment by yerdu** [comment]
I'm having the same issues. They raise prices and never lower them.

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading/
https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/
