### ISSUE TITLE
Better Spawner Control doesn't seem to work

### ISSUE THREAD

**Issue by Nataly171** [ricksouth/serilum-mc-mods#1160]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.54
Environment: Singleplayer

Mod name: Better Spawner Control
Mod version: 1.6

## **Description**
Hi! I've been playing with this mod installed and surrounding spawners with 5 torches doesn't actually disable spawning. I don't know how to diagnose this issue, but I can try to provide whatever is needed.

For a little extra context, this happened in the Nether, with spawners generated by the Repurposed Structures mod. I haven't tested in other dimensions or with other structures.

**Comment by Nataly171** [comment]
After some more testing I have confirmed that the spawner control does not work in any situation. Seems like this should be a high priority bug.

**Comment by Grumpey102** [comment]
Can confirm, still doesn't work with newest 1.19.2 version (betterspawnercontrol-fabric_1.19.2-2.0.jar)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! Apologies it took so long for me to get to. This has been fixed in version 3.0 of Better Spawner Control, along with improved performance by resetting the mob spawner delay when a spawn is denied.

https://www.curseforge.com/minecraft/mc-mods/better-spawner-control
https://www.curseforge.com/minecraft/mc-mods/better-spawner-control-fabric
