### ISSUE TITLE
Infinite villager trading (fabric) Will not go back to normal after uninstalling

### ISSUE THREAD

**Issue by tasobaso** [ricksouth/serilum-mc-mods#1171]
Minecraft version: 1.19
Modloader: Fabric
Multiplayer

Infinite villager trading

## **Question**
Alright so i deleted it from my mods folder on my server panel and restarted the server multiple times. the mod is not in the folder anymore yet im still able to infinitely trade. the reason i removed it was because the villagers would jack up the prices so high after installing the mod and theyd never go down. i afked for 8 hours with a villager and he never lowered his trades.

**Comment by ricksouth** [comment]
The jacking up of the prices has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. The mod can't reset the changes, as variables of the Villager are altered. You'll have to re-place the villagers. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/
