### ISSUE TITLE
Choose what type (biome) of village to spawn in.

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1194]
## **Information**
Mod name: Village Spawn Point

## **Feature description**
Title. I'm very partial to Taiga biomes, but also there's some villages that I find ugly, and would like to stay away from.
This would also add more control to the replayability the mod already adds by spawning you in a village.

That being said, if this gets added, please add support for [Charm's restored/additional villages](https://svenhjol.github.io/Charm/sections/world). I'm even more partial to the Bedrock Exclusive Snowy Taiga villages.

This kind of ties in with #312 and #432. Maybe out of scope of the original vision for this mod, but it would make the whole Minecraft experience so much better, especially since villages are essential nowadays.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
