### ISSUE TITLE
Set World Spawn Doesn't Affect Bonus Chest

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ricksouth/serilum-mc-mods#1206]
As the title states, if you use this mod to change your worlds spawn location and create a new world with a bonus chest, the bonus chest will not be created at the modded world spawn point.  This is, to me, a bug, not a feature request, since if you're moving the world spawn, then the bonus chest should be moved as well.  This also makes me worried that the 'always loaded world spawn chunks' will also not be affected by this mod, and I very much do want my carefully chosen world spawn location to always be loaded just like the normal world spawn is.  Having the modded location always loaded instead of the normal one would be even better, just to avoid the waste of system resources on always loading the normal world spawn as well as the modded one.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by 7OOTnegaTerces** [comment]
Should I repost this over in the new requests forum?!?

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
