### ISSUE TITLE
configure just player heads to drop heads only when killed by players

### ISSUE THREAD

**Issue by BluEagle-Dev** [ricksouth/serilum-mc-mods#1208]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19
Modloader: Fabric
Environment: Multiplayer

Mod name: Just Mob Heads / Just Player Heads
Mod version: (latest 1.19)

## **Question**
Are the mods completly server side or do i need them on client too?

**Comment by BluEagle-Dev** [comment]
Also can i configure just player heads to drop heads only when you get killed by **players**?

**Comment by ricksouth** [comment]
Both mods are server-side needed only. I'll leave this open as a feature suggestion for the second question. Thanks for giving them a try.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by purejosh** [comment]
+10 for this suggestion. I'm definitely wanting to see an "only on player kill" option for head drops.

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
