### ISSUE TITLE
1.19 Recipe Change

### ISSUE THREAD

**Issue by digitaltrucker** [ricksouth/serilum-mc-mods#1215]
## **Information**
Mod name: End Portal Recipe

## **Feature description**
With the release of 1.19 and the new blocks and given the visual appearance of end portal frames, I suggest a change in the recipe (obviously only for 1.19+).

Echo Shard
Sculk Catalyst   -->  Items placed vertically in a crafting table yield one end portal frame block.
Cobblestone

While this will allow players to bypass finding a stronghold to enter the End for the first time it still requires a fair bit of work and personal danger to obtain.  It also allows the dragon egg to be a truly unique item once again.  Portals would also need to be lit in the traditional fashion of inserting eyes of ender.

Optionally, convert the sculk catalyst the warden drops on death into a unique version called a Warden Core and use that in place of the standard sculk catalyst.  That would up the difficulty and time investment massively be requiring a player to kill twelve wardens.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
