### ISSUE TITLE
Takes very, very long to create a new world

### ISSUE THREAD

**Issue by Herobattler** [ricksouth/serilum-mc-mods#1218]
Minecraft version: 1.19
Modloader: Forge 
Forge version: 41.0.105
Environment: Singleplayer

Mod name: Village Spawnpoint (Forge)
Mod version: [villagespawnpoint_1.19.0-1.9.jar](https://www.curseforge.com/minecraft/mc-mods/village-spawn-point/files/3821796)

## **Description**
Takes very, very long to created a new world.

## **Crash report**
Not available due to not being a crash.

**Comment by OysterStew** [comment]
I am having this as well - took over half an hour

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! This has been fixed in version 2.5 of Village Spawn Point, together with the latest Collective update. Will be online as soon as CurseForge approves the file.

https://www.curseforge.com/minecraft/mc-mods/village-spawn-point/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
