### ISSUE TITLE
Mod Idea-Fabric/forge

### ISSUE THREAD

**Issue by AnomalousDeity** [ricksouth/serilum-mc-mods#1220]
immersive Path- when you walk on grass over time it turns into Vanilla paths 
(yes ive seen some other mods but they dont change into vanilla paths just a weird patchy grass spot)

P.s-Love your Mods they are so simple but Unimaginably helpful and effective!

**Comment by Nevrai** [comment]
What are the other mods you’ve seen that do something like this? I’d like to check them out.

**Comment by AnomalousDeity** [comment]
its called Automatic path (fabric), which when walking on grass will turn the grass block into a path, it sorta looks like dirt with few grass spots on it, I was hoping the end result would have been a actual path block like in villages rather than a patchy dirt block

forge version would be desired paths but it hasn't been updated in a long while

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
