### ISSUE TITLE
[Suggestion] [Grindstone Sharper Tools] Require materials to sharpen

### ISSUE THREAD

**Issue by Nevrai** [ricksouth/serilum-mc-mods#1231]
## Information
Mod name: [Grindstone Sharper Tools (Forge)](https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools) (1.18.2)

## Feature description
To prevent the mod from being too powerful, I would suggest requiring materials to sharpen a weapon, based on what the weapon was made of. For instance, to sharpen an iron sword, you’d need, say, two iron nuggets. To sharpen a diamond sword, you’d need two diamond nuggets (which could be added by the mod if no other mod adds them).

I think that’d be a great feature!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
