### ISSUE TITLE
[Naturally Charged Creepers] Charged Creeper always spawn injured

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1247]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.0.8
Environment: Singleplayer

Mod name: Naturally Charged Creepers Mod
Mod version: naturallychargedcreepers_1.19.2-2.0.jar

## **Description**

![2022-08-11_17 52 05](https://user-images.githubusercontent.com/100399264/184102489-7bdc22a6-eab7-40c3-a2ee-59ec5f23c960.png)

Charged Creepers always spawn 5 hp injured, both natural spawn and spawn egg.
Like they're hitted with invisible lightning when they spawn.

**Comment by James103** [comment]
1. Does running `/summon creeper` repeatedly produce a charged creeper? If so, does the `/summon`ed charged creeper spawn with less HP than its max?
2. Does running `/summon creeper ~ ~ ~ {Health:3.0f}` repeatedly eventually produce a charged creeper that dies immediately due to being spawned with less than 5 HP then getting hit by lightning?
3. Does using the spawn egg generated by `/give @s creeper_spawn_egg{EntityTag:{Health:3.0f}}` eventually produce a charged creeper that dies immediately (similar to in case 2)?

**Comment by RedBeast1959** [comment]
1. Yes.
2. lol charged creeper immediately died XD But no lightning effect. Just charged creeper die instantly
3. Yes. Same as 2

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.3 of Naturally Charged Creepers. You'll also need to update Collective to the latest version.

https://www.curseforge.com/minecraft/mc-mods/naturally-charged-creepers/files
