### ISSUE TITLE
Frogs not dropping frog light

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1254]
## **Information**
Minecraft version: 1.19.1
Modloader: Forge / Fabric
Forge version: 42.0.1
Environment: Both Singleplayer & Multiplayer

Mod name: alllootdrops-common (Is what i guess is causing this)
Mod version: 2.5

## **Description**
Made a froglight farm.
Only things that drop are magma cream and magma cube heads.
I think frogs "kill" magma cubes instead of eating them

## **Crash report**
If available.

**Comment by James103** [comment]
Are you able to reproduce this in single player?

> I think frogs "kill" magma cubes instead of eating them

That's true, but the loot tables for Magma Cubes include a condition, which, when triggered by a frog eating a small magma cube (thereby killing it), causes them to drop frog lights instead of their normal drops. All Loot Drops uses a player to generate the possible loot for each mob on server start; therefore, when a mob is killed, its drops will be as if killed by a player regardless of the actual killer.

**Comment by EightBitBBQ** [comment]
Downloaded my server world. Started in SP.
Still the same result

*EDIT* Even let the farm run for 15 minutes.. Still no froglights..
I can see frog eating the magma cubes. Only to spit out cream and cube heads

**Comment by EightBitBBQ** [comment]
Any ETA on this?

**Comment by ricksouth** [comment]
This has been fixed in version 2.6 of All Loot Drops. Thanks for opening the issue and letting me know!

https://www.curseforge.com/minecraft/mc-mods/all-loot-drops/files
