### ISSUE TITLE
cant eat food with shield equipped, super annoying...

### ISSUE THREAD

**Issue by Aikirob** [ricksouth/serilum-mc-mods#1262]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 1.19 latest
Environment: Singleplayer

Mod name: passive shield
Mod version: 1.19 latest

## **Description**
when right clicking to eat food it raises shield instead of eating the food, super annoying.

**Comment by ricksouth** [comment]
I've double checked this, but the problem you are having is not caused by Passive Shield. I don't change any of the eating behaviour, it just hides the shield when it's not active. In my testing I am able to eat with the shield equiped, and when the hunger is full I can use the shield again. I appreciate you giving the mod a try though, hope you can find the problem.
