### ISSUE TITLE
Ideas for Hand Over Your Items mod

### ISSUE THREAD

**Issue by Phaxius** [ricksouth/serilum-mc-mods#1267]
## **Information**
Mod name: Hand Over Your Items

## **Feature description**
There are a couple things in the config that might make it easier not to accidentally use this feature.  One thing would be to have the minimum and maximum distance from player to player configurable.  Often when we are building we are also sneaking so if someone comes too close to us next thing you know they are grabbing up on our items by accident.  It gives the goldilocks zone so to speak if you have a certain range on things.  The next idea is having the ability to toggle a confirmation of some sort when triggering the function.  In a similar way, if it verifies you actually want to give items it can help avoid accidental transfer to some extent.  Given that confirmations are kind of annoying under some circumstances to some people it prompted me to say it would be good to be able to toggle it on and off.  Another potential control would be to allow for turning the ability to hand over items on and off completely.  Given how many things use keybinds maybe it might be good to have the option to toggle the ability through a command potentially but maybe optionally through a keybind (maybe if you can have a prefix like ctrl+(g as default) or something if that makes sense.  Anyways great work, keep it up!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
