### ISSUE TITLE
Will it be possible to have a 1.19 version of the latest update for village spawnpoint?

### ISSUE THREAD

**Issue by cymophic** [ricksouth/serilum-mc-mods#1280]
Minecraft version: 1.19
Modloader: Forge / Fabric
Environment: Singleplayer / Multiplayer

Mod name: Village Spawnpoint

## **Comment**
I have been waiting for a long time for a 1.19 update for the village spawn point since the recent versions had the 0% loading screen error. Now the new update fixes it, but I saw that it's only for 1.19.2. Would it be possible for a backport to 1.19?

**Comment by ricksouth** [comment]
Unfortunately there won't be. At the moment I've got 6 versions to keep active, and 6 extra collective library versions. If I don't work with the latest subversion, that would add 4 extra files with each update.

Sometimes editing the mods.toml works, but since there are changes in Collective for this as well and there were breaking changes in 1.19.1 that's not going to work either.

Sorry for the inconvenience, but I recommend updating to the latest 1.19.2. Thanks for the interest!
