### ISSUE TITLE
Add config option to Village Spawn Point to set forced y coordinate value

### ISSUE THREAD

**Issue by Jetpack-Cat** [ricksouth/serilum-mc-mods#1281]
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.39

Mod name: set world spawn point & village spawn

Mod version: 
Set world spawn point: setworldspawnpoint_1.16.5-2.5.jar
Village spawn point: villagespawnpoint_1.16.5-2.5.jar

## **Question**
I can't find my feature request but I got a notification you closed it as completed, but I'm trying to spawn players  255 blocks ABOVE a village. I had asked for compatibility between these 2 mods for that reason. With both of them installed, even on older versions it wasn't possible, it would spawn you on the ground even if the y offset in setworldspawnpoint was 255. If I remove village spawn point, it will allow me to spawn in the air, but with it it won't. The changelog says you changed it to prevent players from spawning in the air, but it was already this way with both of them installed.

I want the player to spawn at y=255 above a village, and fall to the ground(I have ways to prevent death - this mechanic goes with the storyline of the modpack). Currently I'm using a data pack to spawn them in the air, but there's a delay so I'd rather use these mods.

**Comment by ricksouth** [comment]
Ah apologies. There was another bug where the two mods did not play well together. I have turned this into a feature request for Village Spawn Point.

In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
