### ISSUE TITLE
Beautified Chat prefix and suffix

### ISSUE THREAD

**Issue by SrRapero720** [ricksouth/serilum-mc-mods#1285]
## **Information**
Minecraft version:1.18.2
Modloader: Forge
Forge version: 40.1.73
Environment: Multiplayer

Mod name: Beautified Chat
Mod version: 1.1

## **Question**
It possible use LuckPerms or FTBRanks to get prefix and put into chat (like essentialsX)?

**Comment by SrRapero720** [comment]
![image](https://user-images.githubusercontent.com/29090346/187791442-91cbca96-5947-4d74-87fa-51713fba1abf.png)

**Comment by ricksouth** [comment]
At the moment it is not, but I'll set this as a feature request. Thanks for the interest!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by Illios42** [comment]
I was gonna suggest something very similarly; There is a serious lack of stylised chat mods for forge and it's a huge struggle for server owners so we'd love to see this implemented!

**Comment by Shuro** [comment]
I agree, this would be awesome.

**Comment by SrRapero720** [comment]
Maybe this is a arbitrary comment. but is necesary have a mod to collect all placeholders like bukkit
The problem... any mod creator need to implement "placeholdermod" to work (included luckperms or ftbranks) because forge din't have tools for it.

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
