### ISSUE TITLE
[Suggestion] [Rain Be Gone Ritual] Config option to modify range

### ISSUE THREAD

**Issue by Nevrai** [ricksouth/serilum-mc-mods#1291]
## Information
Mod name: [Rain Be Gone Ritual (Forge)](https://www.curseforge.com/minecraft/mc-mods/rain-be-gone-ritual) (1.18.2)

## Feature description
I think it’d be fantastic if you could add a config option to change the range of effectiveness of the ritual. I couldn’t find any information on the mod page about range, so I assume it stops all rain from occurring. I’d love there to be a config option to set the range at which this works—such as preventing range within a radius of 3 chunks in each direction from the ritual, for instance. I think that’d be much nicer than just preventing all rain from happening in the world/dimension!

Even better would be the ability to expand upon the ritual, starting with a low range (e.g., preventing rain in the chunk/chunks the ritual is placed in) but being able to increase it by adding something. But even just a config option to change the range within which the ritual affects would be superb!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
