### ISSUE TITLE
just player heads x geyser skin api possible?

### ISSUE THREAD

**Issue by onebeastchris** [ricksouth/serilum-mc-mods#1292]
## **Information**
Mod name: Just Player Heads

## **Feature description**
I'm using the awesome plugin [geyser](https://github.com/GeyserMC/Geyser) to allow bedrock players to play on the server. With the help of their other plugin, floodgate, bedrock players can join without needing to use a java account. (unlike offline mode, java player authentication with mojangs servers is unchanged - the only change is, that bedrock players instead get authenticated with the bedrock xbox auth system, and then get a floodgate uuid (bedrock uuid with a filler to effectively make it the java format) on the server. This doesn't allow any pirated clients, on both bedrock and java, to join.

Now since the mod depends on the mojang api to get skins, i was wondering, if it would be possible to use their api for floodgate uuids to make this mod work with bedrock players joined by geyser [Link to their api documentation](https://wiki.geysermc.org/floodgate/features/#what-is-skin-uploading) - alternatively, there is an api that allows the lookup for player head skinfiles for both java and bedrock players via their java or floodgate uuid's [link to the tydium skin api](https://tydiumcraft.net/docs/skinapi)
Would it be possible to allow players to change the origin of the skin file/the api to create support for geyser+floodgate? 

Thank you so much for the awesome, up-to-date mod library, and thank you for reading!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
