### ISSUE TITLE
[Feature] Shulkers spawned via Shulker duplication no respawn on death

### ISSUE THREAD

**Issue by floral-qua-floral** [ricksouth/serilum-mc-mods#1293]
## **Information**
Mod name: [Respawning Shulkers](https://modrinth.com/mod/respawning-shulkers)

## **Comment**
Description states:
> Respawning Shulkers is a mod which makes the process of farming shulker boxes sustainable. Shulkers can quickly become difficult to find in a world, because of the usefulness of shulker boxes. Normally you'd have to find new shulker spawns after your first farming trip.

This is untrue. Vanilla already has sustainable Shulker farming mechanics in that when a Shulker is hit by a Shulker bullet, whether its own or another Shulker's, it has a chance to spawn a new Shulker. [Here is the section on their Minecraft Wiki article about this behaviour.](https://minecraft.fandom.com/wiki/Shulker#Post-generation) It has been used to make completely sustainable Shulker farms in vanilla, such as [this particularly impressive one.](https://www.youtube.com/watch?v=RRSnya62snY)

I would suggest changing the description to instead state that the mod is intended to make sustainable Shulker farming _easier,_ rather than claiming to be making sustainable Shulker farming _possible._ A conventional Shulker farm usually involves transporting Shulkers a long distance and constructing a specially-designed farm, whereas the mod allows a player to stay at one End City and fight Shulkers indefinitely until they have enough; this convenience is a much better "selling point" than the claim that the mod makes Shulker farming possible. This behaviour was added in 1.17, so the description could also point out that it brings sustainable Shulker farming to 1.16.5.

It may also be worth making it so that Shulkers spawned via Shulker duplication won't respawn on death. Otherwise, vanilla-style Shulker farms would generate an ever-increasing number of Shulkers respawning in the farm's kill mechanism, multiplying the farm's effectiveness over time with no upper bounds.

**Comment by ricksouth** [comment]
I've changed the description to be more accurate, thanks for enlighting me. I did not know that the duplication mechanic existed.

I'll leave this as a feature request. Appreciate it!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
