### ISSUE TITLE
Configurable Mob Drops--Feature Request

### ISSUE THREAD

**Issue by CapeSword** [ricksouth/serilum-mc-mods#1316]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod name: Configurable Mob Drops

## **Feature description**
I was trying to figure out how to implement random mob loot drops from the config file. For example, if I wanted to preset the zombie to drop 1 iron or 2 iron with a 75% chance when killed, I understand how to do it. What's not clear is if I want it to drop 0-2 iron without having to log into the game to set that up individually in my world.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
