### ISSUE TITLE
Collective Fabric Crash with Doctor Who Mod

### ISSUE THREAD

**Issue by AzureDoom** [ricksouth/serilum-mc-mods#1318]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: Collective Fabric
Mod version: 4.56

## **Description**
Try placing a Tardis and the game crashes. Happens only with the two mods installed. 

## **Crash report**
My modpack crash log:
https://gist.github.com/AzureDoom/97d39eef56693f2bdfda1d33d2ba0a70

Just the two mods installed:
https://gist.github.com/AzureDoom/70f363b42639545b85f33f320cd2319c

Looks to be an issue with https://github.com/ricksouth/serilum-mc-mods/blob/master/sources/Collective/src/main/java/com/natamus/collective/events/CollectiveEvents.java#L69-L92

Reported to the Doctor Who mod as well.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I think the cause is that the Doctor Who mod hasn't correctly run the WorldLoadEvent prior to loading the dimension.... but this is also my fault for not adding redundency for that. I have fixed it in version 4.57 of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
