### ISSUE TITLE
Full Heal on Level up

### ISSUE THREAD

**Issue by CapeSword** [ricksouth/serilum-mc-mods#1320]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

## **Feature description**
I just thought of an idea for a mod I don't know how to make myself. The idea is to give the player a small reward for leveling up. Since experience and levels aren't meant to do more than pay for enchantments and similar magic, it occurred to me it might not be out of line to give the player a full heal back to full hearts for leveling up. Maybe remove poison or other negative status effects if that's not going too far.

**Comment by ricksouth** [comment]
I do like it! Unfortuantely right now I'm swamped with the bugs that are left, but I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
