### ISSUE TITLE
Stack Refill: Crash when eating food

### ISSUE THREAD

**Issue by Redgycide** [ricksouth/serilum-mc-mods#1325]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 2.5

## **Description**
Hi! It's me again, back with another bug (thanks for the super quick response last time btw!). This time I'm getting a crash from Stack Refill every time I eat food. I just updated Collective and Stack Refill today and that's when the crash started occurring. If it helps at all, the crash happens at the end of the eating animation, right before it does the burp.

## **Crash report**

[crash-2022-09-18_11.08.06-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9594386/crash-2022-09-18_11.08.06-client.txt)

**Comment by ricksouth** [comment]
Ah this was because I've set the version wrong. There was apparently already a version 2.6 and I uploaded the fix as version 2.5. So the launcher made you download the "newer" version, which was actually older. My fault!

I've uploaded it now as version 2.7, which should fix the problem. Thanks for opening the issue and letting me know!

https://www.curseforge.com/minecraft/mc-mods/stack-refill-fabric/files
