### ISSUE TITLE
Crashing with Dynamic Surroundings Resurrected

### ISSUE THREAD

**Issue by Matt577** [ricksouth/serilum-mc-mods#1326]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.68
Environment: Singleplayer

Mod name: Stack Refill (Forge)
Mod version: 3.0

Crashing
Showing the Mojang studios splash briefly before crashing, Minecraft launcher shows The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.sndctrl.audio.SoundUtils
previous versions of stackrefill did not have this crash 

[crash-2022-09-22_19.27.18-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9630132/crash-2022-09-22_19.27.18-client.txt)

**Comment by ricksouth** [comment]
I can't find anything related to Stack Refill. I've opened an issue on their end, and will wait for more information. Thanks for giving the mod a try!

**Comment by ricksouth** [comment]
Closing this for now because Dynamic Surroundings Resurrected hasn't been updated in a while. I'm definitely open to any code changes, but can't find anything I can do on my end in the reported log. You can change to the previous Stack Refill if you'd like compatibility I suppose! Appreciate you giving the mod a try.
