### ISSUE TITLE
1.19.0 updated for Collective-fabric

### ISSUE THREAD

**Issue by giblinjp** [ricksouth/serilum-mc-mods#1333]
## **Information**
Minecraft version: 1.19.0
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer

Mod name: Collective Fabric
Mod version: thats the problem

I am trying to configure a 1.19.0 setup, and have everything working fine, EXCEPT for this mod, which needs to be running version 4.68 or higher, according to the launch screen. However, all versions that recent do not work with 1.19.0

Is there a way to force the game to run it anyway, or could a 1.19.x updated be released?

Thanks!

**Comment by jd-santos** [comment]
Same issue for this and Shulkers. I imagine a lot of server admins don't rush to update to the newest dot release while waiting for mod compatibility to catch up, and if this is intended behavior it will be difficult to use Serilum mods going forward.

**Comment by ricksouth** [comment]
Minecraft's code changed in the subversions of 1.19 due to the new chat features. This makes Collective just not able to run for both 1.19 and 1.19.2. I have to choose which version I develop for, which will always be the latest version.

If you are using the curseforge launcher, the correct file will automatically be chosen for you. If you don't, you can always sort for the correct versions on the website. Click on files and in the top right there's a drop-down menu where you can choose 1.19.

Here's a direct link as well: https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all?filter-status=1&filter-game-version=2020709689%3A9186

Again, it's not really a choice which version I support in this case. I appreciate the interest in the mods!

**Comment by ricksouth** [comment]
I do recommend updating to the latest version, to receive the correct support and bug fixes. But hope this fixes your problem nonetheless.
