### ISSUE TITLE
Mineral Chance: Option to use a loot table to determine the mineral(s) dropped when dropping one

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1347]
## **Information**
Minecraft version: 1.19
Modloader: Fabric

Mod name: Mineral Chance

## **Feature description**
The config file for Mineral Change could include an option, which, when given the ID of a valid loot table, means that when mining a block and it would drop a mineral, the loot table is evaluated and the result dropped.

For example, one could set the loot table to be that of redstone ore to always drop additional redstone when mining a stone block and it would drop an extra mineral.

**Comment by SamuelDancing** [comment]
To add onto this suggestion, maybe even adding a basic loot table to the config options so we can use this mod to make say, Zinc Nuggets from Create drop from overworld stone.

**Comment by ffuentesm** [comment]
That is something I have wondered if it could be able to add moded ores to the drop list. Like getting zink, aluminum, and invar,  when you install mods like thermal or IE.

All you need is a config file, probably json file with a list of blocks and under those block types, a list of items to drop. 
Like 
`minecraft:stone{
minecraft:iron_nugget,
minecraft:gold_nugget,
minecraft:diamond,
minecraft:emerald,
create:copper_nugget,
create:zinc_nugget,
tconstruct:cobalt_nugget}
`

**Comment by James103** [comment]
Allowing for the possibility of a loot table (as described) would also solve https://github.com/ricksouth/serilum-mc-mods/issues/1649 and https://github.com/ricksouth/serilum-mc-mods/issues/1637, as both issues may have existing solutions in loot table form.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
