### ISSUE TITLE
Followers Teleport Too - Waystones compat?

### ISSUE THREAD

**Issue by n0proxy** [ricksouth/serilum-mc-mods#1354]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Followers Teleport Too

## **Feature description**
I was crossing my fingers that the Followers Teleport Too function would work with the teleporting done by the popular [Waystones mod](https://www.curseforge.com/minecraft/mc-mods/waystones)... but it seems not. I would give up a limb to have this loophole filled!

I marked this as +feature rather than incompatibility as technically these mods don't cause problems with each other, so it's not an 'emergency'. But this was really the primary use case that I wanted Followers Teleport Too for xP

**Comment by Darkosto** [comment]
Hello! I just discovered the same issue and was hoping there may be a way to add compatibility? Thank you for this mod!

MC: 1.18.2
Forge: 40.2.0

**Comment by Darkosto** [comment]
Just wanted to leave this here, I contacted the Waystones dev and there is now a teleport event that can be listened to for compatibility: https://github.com/TwelveIterationMods/Waystones/commit/8e215164353e2aab182b091551d15e59fc8fd6b4

**Comment by ricksouth** [comment]
> Just wanted to leave this here, I contacted the Waystones dev and there is now a teleport event that can be listened to for compatibility: https://github.com/TwelveIterationMods/Waystones/commit/8e215164353e2aab182b091551d15e59fc8fd6b4 

Appreciate it! I'll take a look at adding the compatibility.

**Comment by n0proxy** [comment]
Still dying to have this compat added

**Comment by generikb** [comment]
Just chiming in, would love to have Waystones compatibility (pretty much every modpack out there uses Waystones!)

currently on 1.19.2 and 1.20.1 Forge

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
