### ISSUE TITLE
Ability to easily restore backups for others

### ISSUE THREAD

**Issue by MattiDragon** [ricksouth/serilum-mc-mods#1358]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Mod name: Death Backup

## **Feature description**
It'd be nice for admins to be able to restore backups for other players without the use of  `execute as OtherPlayer run deathbackup load 0`. Also proper permission api support would be nice: https://github.com/lucko/fabric-permissions-api

**Comment by maplepy** [comment]
> execute as OtherPlayer run deathbackup load 0

wait is that a command?

**Comment by MattiDragon** [comment]
> > execute as OtherPlayer run deathbackup load 0
> 
> wait is that a command?

Yes, the execute command can do that and much more.

**Comment by Whitebrim** [comment]
Bump

**Comment by maplepy** [comment]
We have switched to https://modrinth.com/mod/deathlog which does the same thing with some extra features and you can easily restore the items

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
