### ISSUE TITLE
Would it be possible to configure spider webs spawned by different spiders

### ISSUE THREAD

**Issue by PuppetMasterZee** [ricksouth/serilum-mc-mods#1359]
## **Information**
Minecraft version: 1.19.2
Modloader: Quilt
Quilt loader version: 0.17.4
Environment: Multiplayer

Mod name: spidersproducewebs-fabric
Mod version: 1.19.2-2.1

## **Question**
Would it be possible to configure spider webs spawned by different spiders?  I would like to use this mod, but in testing the webs are causing quite a few problems in mob farms.  I think it could be a good balance if we could disable the standard spiders from being able to make cobwebs, but be able to retain cave spiders being able to make cobwebs.
Thanks for your consideration.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
