### ISSUE TITLE
it comes with a cost

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [ricksouth/serilum-mc-mods#1360]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

## **Feature description**
if you cen just keep sharping it it becomes a little too op but if you cen enable an option in the config that when you sharp it its durability gets lower becouse it real life to much sharping a sword will oversharp it which means that the sword loses to much material on the blade which makes sword more fragile

**Comment by James103** [comment]
In other words, when sharpening an item on a grindstone with this mod, the item takes X durability damage, where X is a configurable number.

For example, sharpening an Iron Sword may give it 50 sharpened uses at the cost of 25 durability (or less with Unbreaking).

**Comment by ShadowSlayerFX1** [comment]
yes so you cant keep sharping it without something in return

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
