### ISSUE TITLE
[Suggestion] Multiple starter kits to choose from

### ISSUE THREAD

**Issue by FJDoell** [ricksouth/serilum-mc-mods#1373]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge / Fabric

Mod name: Starter Kit

## **Feature description**
At the start of a world, the player is presented a list of starterkits to choose from instead of just one. With mods this could get even crazier, like starting with a magic book, starting with 1 extra heart but no gear, etc.

I think this could provide some interesting agency in a player's playstyle, even from the start. :)

As for implementation, I'd rework it to have each option be a file name instead of just reading starterkit.txt. You could even have this trigger only if multiple starterkit files are present.

So for example, my starterkit folder contains: knight.txt, scout.txt.
Options come up at start of world: Knight, Scout. Pick one and read that starterkit file. Rest of the process can be re-used seamlessly. :)

**Comment by Darkmega18** [comment]
please and thank you. I'm sure someone will find a use for this one.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thank you again for the feature request!

I've been working hard on lots of new features for Starter Kit these past few days. Version 6.0 is now available on CurseForge and Modrinth. It contains many new features, and this one has been added too :) Hope you enjoy them!

https://legacy.curseforge.com/minecraft/mc-mods/starter-kit

**Comment by Darkmega18** [comment]
:O very nice. if I get back into modding and playing MC hopefully I'll make use of them.
