### ISSUE TITLE
[Suggestion] Enchanting Commands Mod - Increasing the enchantment level limit.

### ISSUE THREAD

**Issue by FireGeneral** [ricksouth/serilum-mc-mods#1374]
## **Information**
Minecraft version: 1.17, 1.18, 1.19
Modloader: Forge / Fabric

Mod name: Enchanting Commands

## **Feature description**
This mod is really useful, but it's very limited with the maximum supported enchantment level being only 127 (If I remember correctly)
Most people should know that Minecraft introduced enchantment limit 255 to the game after version 1.17, which can't even be bypassed with command blocks. There're only a few mods out there which claimed to have removed the limit, and all of which I could find are proven to be broken.
My suggestion is that I wish to have this mod increase its enchantment level limit. It's not needed to have the mod allow enchantment level more than 32767, since it's the reason why Mojang added the limit in the first place (MC-131290). For me, I wish the mod to at least be able to produce enchantment level around 500. Thank you!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
