### ISSUE TITLE
GUI Clock Settings Improvements

### ISSUE THREAD

**Issue by Obscure2020** [ricksouth/serilum-mc-mods#1380]
## Information
Minecraft version: 1.19.2
Modloader: Fabric

Mod name: GUI Clock

## Feature Descriptions
I've been using GUI Clock for over a year now, and I believe its config menu needs some work.
Before I start listing improvements I'd like to see, let me first say how happy I am that it **_has_** a menu now!
Wasn't long ago I had to edit a config file manually every time I needed to adjust it.

Here's what I'd like to see changed:
1. `_24Hourformat` should be renamed to `Real Time Format`, and the button's options should be changed from `Yes` / `No` to `12-Hour` / `24-Hour`.\
![image](https://user-images.githubusercontent.com/69320464/197061334-bc766d5c-3ef9-4194-8b8f-fd356e8fff8b.png)
2. `Clock Height Offset` and `Clock Width Offset` are not optimally named, because they do not modify the height or the width of the clock. These should be renamed to `Clock Y Position Offset` and `Clock X Position Offset` respectively.\
![image](https://user-images.githubusercontent.com/69320464/197061897-7ad3801b-cd0d-4e8a-b283-61e49230cd7c.png)
3. This last one has annoyed me for a long time. This should not be three separate options. This should not be three separate lines in the config menu, nor should it be stored as three separate values in the config file. This is one singular setting. Heck, the mod doesn't even really handle having multiple of these be `Yes`. It'll only ever show the clock in one position.\
This option should not be stored or displayed as three booleans. It should be stored either as a string or as a number, and it should be displayed as a single `Clock Base Position` option. It should have one button, which can be toggled between the options `Left`, `Center`, and `Right`.\
(In case you weren't aware that config buttons could have more than two options, I recommend that you install Item Model Fix and take a look at how its config menu functions.)\
![image](https://user-images.githubusercontent.com/69320464/197062191-72327761-5bd9-46bb-926e-97c2758dc861.png)\
EDIT: Actually, my original recommendation for an example for this point is now out of date. Item Model Fix has been superseded by [Model Gap Fix](https://modrinth.com/mod/modelfix), which does not feature a config menu. Instead, I recommend you install [Fabrishot](https://modrinth.com/mod/fabrishot), and look at the `File format` selector in its config menu.

**Comment by Obscure2020** [comment]
Hey, uh... can you remove the tag `Mod Label Missing`?
I clearly marked this as a Feature Request regarding **GUI Clock.**
I listed GUI Clock both in the title of this request _and_ in the body of this request.
Why is this still marked as `Mod Label Missing`?

**Comment by ricksouth** [comment]
I haven't had the time to go through the new issues on GitHub yet. I have to add labels manually. Been working on the SpookyJam mod this month.

**Comment by Obscure2020** [comment]
How you doing now? On Minecraft 1.20.4, using GUI Clock v4.4, all of my originally-stated criticisms and suggestions for changing the GUI Clock config for the better are still relevant, and all have still not been addressed.

**Comment by Obscure2020** [comment]
Actually, my recommendation for an example for Item 3 is now out of date. Item Model Fix has been superseded by [Model Gap Fix](https://modrinth.com/mod/modelfix), which does not feature a config menu.

Instead, I recommend you install [Fabrishot](https://modrinth.com/mod/fabrishot), and look at the File format selector in its config menu.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by Obscure2020** [comment]
Thanks for the information! I'll keep an eye on the new feature request tracker.
