### ISSUE TITLE
Endermen wont spawn

### ISSUE THREAD

**Issue by ElfKing94** [ricksouth/serilum-mc-mods#1381]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.14.9
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: 3.2

## **Description**
howdy, so i notice endermen dont spawn with this mod for some reason. i have it configured to not pick up blocks and instead im getting no endermen in the end and cant spawn any with the spawn egg. thanks

**Comment by James103** [comment]
Do you get any errors in the server log when an enderman tries to spawn by any means?

**Comment by ElfKing94** [comment]
Um i was just playing on singleplayer. When i turned off the mod everything was back to normal.

**Comment by Cookie-Kurokami** [comment]
I'm having the same problem, assuming this thread is about Passive Endermen. Endermen do not appear and attempting to summon one yields only this error: 
![image](https://user-images.githubusercontent.com/66750372/198815805-fa5a2b22-87ae-4b58-86fd-8e4af40da1c1.png)
This only happens when the mod is installed. Without it, Endermen spawn as normal. Here's the actual error log:
![image](https://user-images.githubusercontent.com/66750372/198815842-798549d7-9849-4546-8434-46fae48116e5.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 5.14 of Collective (Fabric). Passive Endermen does not need an update.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
