### ISSUE TITLE
Player heads drop in PVP only

### ISSUE THREAD

**Issue by LuigiKraken** [ricksouth/serilum-mc-mods#1389]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge / Fabric

Mod name: Drop Player Heads Mod

## **Feature description**
hey love your work. It would be great if you could also configure player heads drop on player kill similar to the mob heads mod. ideally the only what to get your own head without help is by killing yourself with your own arrow.

**Comment by LessThanBenji** [comment]
Would love to see this feature!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by rhysperry111** [comment]
Is there any chance this will be implemented at all? It's already a thing for Just Mob Heads, and there are many situations where it's favourable to do the same for player heads.
