### ISSUE TITLE
Save & Load Inventory Less Hotbar Items?

### ISSUE THREAD

**Issue by DumbXBoxAcct** [ricksouth/serilum-mc-mods#1399]
Love the mod, it's something that Mojang should have put in to begin with!

Is it possible to save and load an inventory without saving or replacing the items in the hotbar?  I tried editing the inventory's text file by (a) deleting the lines for items 0 through 8, (b) putting  a space, two quotes and a comma next items 0 through 8's entries after the colon and (c) just putting a space and a comma after each item's entries after the colon without success.  

When loading, all of those leave the hotbar items in place, but none of the rest of the inventory shows up.  The ideal would be a command line argument that skips or includes the hotbar, for both the /saveinventory and /loadinventory commands, but I'd happily settle for a way to simply edit the inventory's text file instead, if you're able to provide it.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
