### ISSUE TITLE
GUI Clock (NBSP error)

### ISSUE THREAD

**Issue by asica117** [ricksouth/serilum-mc-mods#1400]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 1.19.2
Environment: Singleplayer

Mod name: GUI Clock
Mod version: 1.19.2-3.7

## **Description**
Hello!
After changing some of the parameters at the confing (true or false) to get 12 hours real time showing, this happened.
The clock on the screen has tiny letters error. It says  NBSP.
Here in the image you can see. Hope it can be fixed.
Thank you!

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.
![2022-11-02_21 07 22](https://user-images.githubusercontent.com/117330290/199642560-a0cd9b16-680b-4cf9-9271-23c00784a59c.png)
![Untitled](https://user-images.githubusercontent.com/117330290/199642676-f0ed1cb4-ca43-41f6-8d86-3f90aa2dafb4.jpg)

**Comment by James103** [comment]
`DateTimeFormatter` uses your system's time format to get the proper time string to be displayed when the GUI Clock renders its string showing the current time. It appears your system's time format has a non-breaking space in the "a.m." and "p.m." strings it uses to show time in the 12-hour am/pm format. Since that character is likely not supported in any of the default fonts Minecraft uses, it shows up as a box with its shorthand code (typically Unicode hex code, but some characters override that).

**Comment by ricksouth** [comment]
Thanks for opening the issue and thank you @James103 for working out the problem. I'm now removing any non-breaking space characters in the function that parses the local PC's time. This has been fixed in version 5.19 of Collective. GUI Clock doesn't need an update.

https://www.curseforge.com/minecraft/mc-mods/collective/files
