### ISSUE TITLE
Village Spawn + Biome Spawn

### ISSUE THREAD

**Issue by AngleWyrm10** [ricksouth/serilum-mc-mods#1403]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 1.40.79
Environment: Singleplayer

First mod name: Biome Spawn point
First mod version: 1.0

Second mod name: Village Spawn point
Second mod version: 2.6

## **Description**
With these two mods loaded -- both by you -- starting a new world results in spawning in a village, but not in a chosen biome. I've seen Tiaga village spawns with only Plains enabled for biome spawn

My Village Wizard mod pack uses your village spawn point. It would be nice if I could also add the functionality of your Biome Spawn mod

**Comment by dr3ams** [comment]
For me it doesn't even load (216 mods). 
Hanging on _Preparing spawn area: 100%_ for ages with only 2 biomes selected(plains and forest).

**Comment by ricksouth** [comment]
@dr3ams please make a separate issue for that, with log files. The mod "loads" at 0%, when it goes above that, loading is done. This *should* mean that it isn't the mod causing the issue.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mods a try! This has been fixed in version 1.3 of Biome Spawn Point and version 2.9 of Village Spawn Point. I've added compatibility with both. If both are installed and configured, you now spawn in a village near the biome.

https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point
https://www.curseforge.com/minecraft/mc-mods/village-spawn-point
