### ISSUE TITLE
Biome Spawn point mod incompatibility

### ISSUE THREAD

**Issue by dr3ams** [ricksouth/serilum-mc-mods#1405]
## **Information**
Minecraft version: **1.18.2**
Modloader: **Forge**
Forge version: **40.1.84**
Environment: **Singleplayer**

First mod name: Biome Spawn point
First mod version: 1.0

Second mod name: Village Spawn point (_probably_)
Second mod version: 2.6

## **Description**
Playing a [modpack](https://www.curseforge.com/minecraft/modpacks/life-in-the-village-3) with 216 mods. 
After adding **Biome Spawn point** mod I cannot create new world, it just hangs on _Preparing spawn area: 100%_ for ages.
I can create new world after deleting **Village Spawn point**, that's the first and only mod I tried deleting.

## **Crash report**
[Modlist](https://gist.github.com/dr3ams/54c98568be1f318a46075cde05033154)
[latest.log](https://gist.github.com/dr3ams/f7c174ae089e61809e32462c196d6a8c)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mods a try! This has been fixed in version 1.3 of Biome Spawn Point and version 2.9 of Village Spawn Point. I've added compatibility with both. If both are installed and configured, you now spawn in a village near the biome.

https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point
https://www.curseforge.com/minecraft/mc-mods/village-spawn-point
