### ISSUE TITLE
Furnace recycler additions

### ISSUE THREAD

**Issue by sodalish** [ricksouth/serilum-mc-mods#1406]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod name: Furnace Recycler

## **Feature description**
Could you please add the armors (iron, gold, chain) to the furnace/blast furnace?  Your balance is fantastic and if we can get an ingot from a cauldron why not a chest plate?

Best,
Sodalish

**Comment by ejm554** [comment]
A similar request: Add a config file that will allow players or server owners to customize what can be melted and what the output will be. 

For example, I use the [Coins mod](https://www.curseforge.com/minecraft/mc-mods/coins-je), and I'd love to be able to melt the coins back into the ingots that were used to craft them. I wouldn't expect you to add this specific feature, however, but if you had a config file, I could define it myself.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
