### ISSUE TITLE
Cannot load into any world while only running the Collective library mod

### ISSUE THREAD

**Issue by Master-64** [ricksouth/serilum-mc-mods#1411]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 5.14

## **Description**
Loading into any world will either close the world with a "Disconnected" message or an "Invalid Player Data" error. No other versions appear to work. I also believe this same error occurs on 1.18.1.

## **Crash report**
Not available (also no log file as I don't seem to have one somehow).

**Comment by ricksouth** [comment]
This was caused by Mojang's launcher update they released yesterday. I've fixed all problems I can on my end, but there will probably be other (non-serilum) mods that aren't working correctly still. It seems like client log files aren't generated correctly still.

I've just pushed an update for Collective. It will work correctly now, but hopefully Mojang will push an update either way for all other mods. Thanks for giving the mods a try! :)

https://www.curseforge.com/minecraft/mc-mods/collective-fabric
