### ISSUE TITLE
Error with Collective (Fabric) Library

### ISSUE THREAD

**Issue by SamuelDancing** [ricksouth/serilum-mc-mods#1412]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 5.14

## **Description**
I have been messing around with mods, and while I didn't run into issues earlier, today I opened up a modpack that just started having issues. It boots up just fine, but when I try to load a world, it hits me with "Disconnected: Invalid Player Data" It even happens on new worlds, and when deleting Player Data.

Testing has shown that this mod alone caused the error (which is sad because I love Mineral Chance), and I don't know if it's incompatibility, or just a change that caused some reference to be deleted or whatever is going on. I will include the log file (since there was no crash), but I can't say it'll help since there's no real crash. However, I will include my mod list in case that helps.

## **Mod List (Note: all are Fabric variations, if multiple are available)**
Fabric API 0.59.1
Accurate Block Placement 1.0.12
Apple Skin 2.4.1
Attribute Fix 14.0.2
Balm 3.2.0
Charm of Undying 2.0.2
Cloth Config API 6.4.90
Clumps 8.0.0
Collective 5.14 (This mod, currently inactive)
Comforts 1.1.3
Continuity 2.0.1
Create 0.5.0e
Deepslate From Lava 1.0.0
Fabric Language Kotlin 1.8.5
Fabric Tree Chopper 0.8.6
Waystones 2.5.5
Falling Through 2.5
Forge Config API 3.2.4
Harvest with Ease 4.0.0.1
Indium 1.0.7
Inventory Profiles Next 1.8.3
Inventory Sorting 1.8.8
JourneyMap 5.8.5
KleeSlabs 11.1.1
libIPN 1.0.4
Mineral Chance 2.2 (Inactive)
Mod Menu 3.2.4
More Villagers 3.3.2
Mouse Tweaks 2.22
Netherite Beacons 1.2.0
Sodium 0.4.1
Trade Cycling 1.0.2
Trinkets 3.3.1

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9956950/latest.log)

If available.

**Comment by ricksouth** [comment]
This was caused by Mojang's launcher update they released yesterday. I've fixed all problems I can on my end, but there will probably be other (non-serilum) mods that aren't working correctly still. It seems like client log files aren't generated correctly still.

I've just pushed an update for Collective. It will work correctly now, but hopefully Mojang will push an update either way for all other mods. Thanks for giving the mods a try! :)

https://www.curseforge.com/minecraft/mc-mods/collective-fabric
