### ISSUE TITLE
Disconnect from single player worlds

### ISSUE THREAD

**Issue by wolfnomknight** [ricksouth/serilum-mc-mods#1413]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 5.14

## **Description**
Hey! Whenever I try to enter an existing world or create a new one, I get a "Connection Lost: Disconnected" error, or a "Connection Lost: Invalid player data" error and I'm kicked back to the server selection screen. The strange thing is, I'm in single player.

At first I thought it was a mod conflict, but I unistalled all mods and the problem persists. Currently it's only Collective and the Fabric API. Also, everything was working yesterday.

As soon as I uninstall Collective, the game works as intended - even with other mods loaded.

## **Crash report**
There is no crash log as the game have not crashed.

**Comment by GweshaDeneb** [comment]
I would also like to add since i noticed the same too   
and that collective never ever shows up in the mod list when you load up minecraft  which  is the main reason  it boots out of single playergame and no  log gets created because of it

**Comment by ricksouth** [comment]
This was caused by Mojang's launcher update they released yesterday. I've fixed all problems I can on my end, but there will probably be other (non-serilum) mods that aren't working correctly still. It seems like client log files aren't generated correctly still.

I've just pushed an update for Collective. It will work correctly now, but hopefully Mojang will push an update either way for all other mods. Thanks for giving the mods a try! :)

https://www.curseforge.com/minecraft/mc-mods/collective-fabric
