### ISSUE TITLE
Omegamute suddenly stopped working

### ISSUE THREAD

**Issue by Gabann** [ricksouth/serilum-mc-mods#1414]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer and Multiplayer

Mod name: Omega Mute (Fabric)
Mod version: 2.7

## **Description**
Hi, when i logged in today i instantly noticed omegamute stopped working.
I tried to reload the config file ingame but it didn't work
I tried to delete the omegamute config folder but the mod does not generate a new one

Maybe this bug is related to the new bug where you can't load any single player world? (issue related links below)
https://github.com/ricksouth/serilum-mc-mods/issues/1413
https://github.com/ricksouth/serilum-mc-mods/issues/1411

## **Crash report**
I don't have any

**Comment by ricksouth** [comment]
This was caused by Mojang's launcher update they released yesterday. I've fixed all problems I can on my end, but there will probably be other mods that aren't working correctly still.

I've just pushed an update for Omega Mute. It will work correctly now, but hopefully Mojang will push an update either way for all other mods. Thanks for giving the mod a try! :)

https://www.curseforge.com/minecraft/mc-mods/omega-mute-fabric
