### ISSUE TITLE
Village Spawn blacklist option

### ISSUE THREAD

**Issue by brisingraerowing** [ricksouth/serilum-mc-mods#1423]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Village Spawn Point

## **Feature description**
Repurposed Structures adds an Ocean village that is underwater and filled with Drowned. I've had a couple seeds spawn me in one now, and it's a death trap. A blacklist of village structures would be nice to have so this can be prevented.

**Comment by jeffrash** [comment]
I've had the same thing happen to me twice today.  This would be a great new feature.

**Comment by brisingraerowing** [comment]
I've managed to get it sorta working with Biome Spawn Point. I do still sometimes spawn in an ocean village.

**Comment by jeffrash** [comment]
I fixed it by disabling the ocean village in repurposed structures with a simple datepack config change.  That's not a village I would be visiting very often anyway.  You can find a working example in version 1.1 of my mod pack (Ozoneman42's Pack) on Curseforge.

**Comment by SettingDust** [comment]
Fixed by https://modrinth.com/mod/serilum-spawn-tweaker ~~(Under Review 2023.10.31)~~

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
