### ISSUE TITLE
Custom books not working

### ISSUE THREAD

**Issue by zoeyisevil** [ricksouth/serilum-mc-mods#1424]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer / Multiplayer

Mod name: Starter Kit
Mod version: 3.9

## **Description**
Custom book isnt working :(

## **Crash report**

[message_3.txt](https://github.com/ricksouth/serilum-mc-mods/files/10003905/message_3.txt)

my config :
[starterkit.txt](https://github.com/ricksouth/serilum-mc-mods/files/10003919/starterkit.txt)

I asked a friend to inspect maybe this will help ;A; ?
![image](https://user-images.githubusercontent.com/102392496/201686791-43b6bf10-6b74-432e-859d-3ef62d11b681.png)
![image](https://user-images.githubusercontent.com/102392496/201687314-2a1922d8-060a-4cb7-bbe7-808c34a20da6.png)

**Comment by ricksouth** [comment]
Hmm, I think this is because there is the line

"... Note : All ..."

inside the book.

That's my fault for not parsing it correctly. For now I think the following file should work:
[starterkit.txt](https://github.com/ricksouth/serilum-mc-mods/files/10003994/starterkit.txt)

(I changed Note : to Note:) Does that work?

I'll leave this open as a bug report though! Thanks for opening it.

**Comment by zoeyisevil** [comment]
oh thank you thank you :'D! ill see if it works

**Comment by zoeyisevil** [comment]
it worked, yeah. Thanks!

**Comment by ricksouth** [comment]
Thanks for confirming! Apologies for the inconvenience. I'll push a fix when I can to make it work in the future :)

**Comment by ricksouth** [comment]
This has been fixed in Starter Kit 4.0, together with the latest Collective update. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
