### ISSUE TITLE
starter kit 1.18.2 item with nbt 

### ISSUE THREAD

**Issue by alessandriLuca** [ricksouth/serilum-mc-mods#1426]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.1.73 
Environment: Singleplayer 

Mod name: Mod
Mod version: 3.9

## **Question**
Everything works fine besides for the chest. I copied exactly what i obtained from the command /data get entity @s SelectedItem
The chest is not loaded. 
[starterkit.txt](https://github.com/ricksouth/serilum-mc-mods/files/10016734/starterkit.txt)

**Comment by ricksouth** [comment]
I think this is because the mod can't parse both "'s and 's in the list. I should probably add compatibility for that.

For now the best solution would be to use the

/starterkit set

command. This will put your entire inventory in the config file. Thanks for opening the issue and giving the mod a try!

**Comment by alessandriLuca** [comment]
That worked !!! Thanks ;))

**Comment by ricksouth** [comment]
Support has been added in Starter Kit 4.0, together with the latest Collective update. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
