### ISSUE TITLE
Server not spawning player in a village with Biome spawn point and Village spawn point

### ISSUE THREAD

**Issue by dr3ams** [ricksouth/serilum-mc-mods#1428]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.1.84
Environment: **Multiplayer**, [Life in the village 3 modpack](https://www.curseforge.com/minecraft/modpacks/life-in-the-village-3)

First mod name: Biome Spawn point
First mod version: 1.5

Second mod name: Village Spawn point
Second mod version: 2.9

## **Description**
Server having trouble spawning player in chosen biome and in a village at the same time. Spawning only in a biome but not in a village. Not sure if that's incompatibility between these two mods. Logs and conversation screenshots included.
![image](https://user-images.githubusercontent.com/7347489/202557882-4ddcb5b1-eff7-43a7-b146-a951210ac755.png)

World seed used in example: 9110335844545486551
Spawned in minecraft:meadow (enabled in a list) but nearest village in 1000 blocks away
![зображення_2022-11-17_225416467](https://user-images.githubusercontent.com/7347489/202556684-f6400082-739b-4788-af6f-b2ce7546d27b.png)

https://gist.github.com/dr3ams/4caf8cfcdd865ee1a9a330cb09a3a378

**Comment by ricksouth** [comment]
Thanks for opening the bug report! This was due to the code I'm using in Collective to simulate the /locate command not working correctly server-side. I've just uploaded version 5.17 of Collective which fixes the problem. Biome/Village Spawn Point also got a small update to fix a compatibility issue and improved logging. Appreciate you giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point
https://www.curseforge.com/minecraft/mc-mods/village-spawn-point
