### ISSUE TITLE
[Suggestion for Random Mob Effects] RNG-Dependent Option In Config

### ISSUE THREAD

**Issue by ZilverLazarus** [ricksouth/serilum-mc-mods#1439]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Random Mob Effects

## **Feature description**
So I've been making a modpack for the past 2 years, and I've been looking for mods that make mobs more interesting to fight (which includes the likes of Improved Mobs, Enhanced AI, and Infernal Mobs). Random Mob Effects does add onto this and I have to thank you for making the mod.

However, it does have one thing that I do need to address. The only point of feedback I have is when I was looking into the config, I was disappointed to see that there is no 'chance of effect' option/range, making all mobs always have a random effect. Don't get me wrong, it's interesting to see all mobs have some random effect, but I personally think there should be a random chance option instead of it always being guaranteed. 

Hopefully this suggestion is considered and again, thank you for your hard work. Your mods add a lot of QoL features and are very helpful for players and modpack developers like me.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
