### ISSUE TITLE
A few ideas for Grindstone Sharper Tools

### ISSUE THREAD

**Issue by Delfite** [ricksouth/serilum-mc-mods#1471]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric

Mod name: Grindstone Sharper Tools (Fabric)

## **Feature description**
1. Add a config option that displays the remaining sharpened uses as a percentage (down to 1 decimal place) instead of as whole numbers. This is especially useful for those who use really large numbers but don't like how odd it looks to have "5000 uses remaining" show up in chat or on the item's name. It would also be nice
2. Add a config option that displays the remaining uses in an item's lore rather than the name. This is to allow for compatibility with the mod Colorful Anvils, which allows players to use colored item names in anvils using the Placeholder API. It also looks a bit nicer overall (especially with the previously mentioned idea)

Here are some concepts as to what they would look like:
![grindstone-concept1](https://user-images.githubusercontent.com/23504262/207943472-7bdf1923-5ed2-4d36-bd77-3e6be7b5ce12.png)
^ Percentages + Lore
![grindstone-concept2](https://user-images.githubusercontent.com/23504262/207944720-dc0abee5-851d-461b-bdd3-70ab4412cbf2.png)
^ Whole Numbers + Lore

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
