### ISSUE TITLE
GST: Stacking Damage Modifiers

### ISSUE THREAD

**Issue by Ariostraza** [ricksouth/serilum-mc-mods#1496]
Minecraft version: 1.19.3
Modloader: Forge

Mod name: Grindstone Sharper tools

Stacking damage modifiers, at the cost of less uses.
For example, say i sharpen two times, the modifier would be +1.5 and add a +1.5 for a total of +3 damage, but would reduce the sharpening durability by 25% so instead of 32 its 24 uses.
on top of that say i sharpen again, that would reduce the durability by another 25% so 16 but add +1.5 so 4.5
In total i gain 4.5 bonus damage but the uses are reduced by half.
I would add these options

Max Stacking: Max ammount of buffs that can be stacked in an item
Use Penatly: % or number of uses that are to be taken away with each stack

Id say default max stacks would be 3 and penatly -%25 or -8 uses
Could be phrased better im kinda tired.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
