### ISSUE TITLE
[Crying Portals] Forced linking

### ISSUE THREAD

**Issue by AlienXtream** [ricksouth/serilum-mc-mods#1500]
## **Information**
Minecraft version: N/A
Modloader: Universal

Mod name:  Crying Portals

## **Feature description**
i know this may go against some of the "vanilla friendly" design you seem to be going for but this would be a nice (and unique) feature to have. basically a portal can only link to a portal with a matching frame pattern (orientation independent). additionally a portal would also have to be of a matching size (immersive portals already does this as its required for its portals to work correctly in most cases). the general idea would be that two portals close to eachother can only generate/link to a matching portal, allowing more control over where and how portals link. the range for the check should be around 16 blocks in the nether to check for a matching portal from the overworld. for the inverse it should only check up to 32 blocks from the equivalent overworld position (because NP hard problem). an arbitrary size limit could be assigned for portals so that anything bigger than, say, a 5x5 portal would revert to vanilla behaviour. i do understand that this is a little more complex than just adding a second block to the vanilla portal validation check and could require some reworking of the actual portal code itself so i can understand if its not something you're interested in doing. its just something that i think should be in vanilla as it does solve a problem that is unintuitive for new players. regardless, its your call if you want to implement such a thing, im just happy to be able to provide the idea :)

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
