### ISSUE TITLE
Is there a config for the "Stack Refill" mod?

### ISSUE THREAD

**Issue by simpl1city** [ricksouth/serilum-mc-mods#1505]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer and Multiplayer

Mod name: "Stack Refill"
Mod version: 3.3

## **Question**
Hi Serilum,

Is there a way to configure this mod? There doesn't seem to be any configuration options in my mod menu for this mod and I can't see any config for it in .minecraft's config folder.

My issue is with using buckets - if I use a water bucket I don't want stack refill to replace it with another one.

Thanks,
simpl1city

**Comment by SpaceNerd95251** [comment]
I'd like to second this

**Comment by EightBitBBQ** [comment]
Currently there is no config. Multiple request have been made. Sadly we will have to wait for now

**Comment by kiran-evans** [comment]
I'd also like to second this. It's very frustrating when the tools are replaced before their durability gets to 0. You just end up with an inventory full of useless tools.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
