### ISSUE TITLE
Grindstone Sharper Tools require a grinding process

### ISSUE THREAD

**Issue by ArchiDreamZ** [ricksouth/serilum-mc-mods#1510]
Mod name: Grindstone Sharper Tools

## **Feature description**
In my opinion, sharpening a knife on the grinding wheel should not just be a right click, if it needs to hold the right button for a few seconds to sharpen the knife, it will be more reasonable and balanced.
Otherwise, the player only needs to carry the grinding wheel with him, and he can sharpen the knife in a very short time. This is just an extra step for the game, and the player will not experience the fun and meaning of sharpening the knife on the grinding wheel.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
