### ISSUE TITLE
Grindstone Sharper Tools requires language files

### ISSUE THREAD

**Issue by ArchiDreamZ** [ricksouth/serilum-mc-mods#1511]
Mod name: Grindstone Sharper Tools

## **Feature description**
![image](https://user-images.githubusercontent.com/89504984/210958448-dd32b508-914c-4ff7-aa9c-9898e5a6f15c.png)
![image](https://user-images.githubusercontent.com/89504984/210958507-90968c3f-336a-41b4-b94b-270823afa616.png)

None of these words can be localized into other languages, which will affect the game playability, most people can't read English

**Comment by ArchiDreamZ** [comment]
I can only write this proposal through a translator

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
