### ISSUE TITLE
Crashing with mismatch version, but Curseforge launcher updated Collective on its own. 

### ISSUE THREAD

**Issue by purejosh** [ricksouth/serilum-mc-mods#1599]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: Multiplayer

Mod name: Collective
Mod version: 6.43

## **Description**
Crashing with mismatch version, but Curseforge launcher updated collective on its own. 

## **Crash report**
https://gist.github.com/purejosh/181d851dc0a17aed05a3a13ec95ae60f

**Comment by ricksouth** [comment]
You'll need to change the inventory totem mod from the fabric version to forge&fabric. So instead of downloading it from
 https://www.curseforge.com/minecraft/mc-mods/inventory-totem-fabric

You'll have to download this version:

https://www.curseforge.com/minecraft/mc-mods/inventory-totem


I recently moved the Fabric files to the main project page, to clean up the projects and make it easier to update in the future.

**Comment by purejosh** [comment]
I should have caught that, my apologies. Thank you very much!

**Comment by ricksouth** [comment]
No problem. Thanks for giving the mods a try! :)
