### ISSUE TITLE
Underground structures?

### ISSUE THREAD

**Issue by Golrith** [ricksouth/serilum-mc-mods#1603]
With the Starter Structure mod, I can make the player spawn underground, but the expected structure spawns at the surface.
Is it possible to have an underground spawn & structure?

**Comment by T0mt4ru** [comment]
I have the opposite issue, I have my underground bunker, but my player spawns on the surface...

**Comment by Golrith** [comment]
With some tweaking of the following configs, both the player and the structure should end up roughly together. Trouble is, the structure is a Offset value, and the player is a co-ord. So depending on worldgen, there's going to be some movement.

"generatedStructureYOffset": -100,
"spawnYCoordinate": 0,

I'm using another mod to drastically increase the height of the underground, so Y=0 isn't that deep. Would love to go deeper!

**Comment by T0mt4ru** [comment]
I have mine set like this:

"generatedStructureYOffset":-8,
"spawnYCoordinate":-1,

This makes my (small) bunker spawn 8 blocks underneath the surface ( I have a ladder leading up) but leaves the player standing on the surface...

Setting a more specific Y value would make the bunker not connect to the surface anymore.

This mod is neat, but lacks some needed flexibility. Like disconnecting the "spawnYCoordinate" from the X and Z coordinates.

I'm also using NBT structures now instead of .schem, as the .schem was always a cube and wouldn't blend in neathly with the surface,

**Comment by Golrith** [comment]
Yep, needs a generatedStructureYCoordinate and spawnYOffset with an option to adjust between offset & coord for maximum flexability.

**Comment by ricksouth** [comment]
Do you have the schematic file for me so I can test it in my development environment? One with an underground structure, and the settings? :)

**Comment by T0mt4ru** [comment]
[bunker_no_mods.zip](https://github.com/ricksouth/serilum-mc-mods/files/10745018/bunker_no_mods.zip)

Simplified version of my underground bunker, as the original has modded items in it.

`{
	// Whether a schematic that's located in './config/starterstructure/schematics/...' should be generated.
	"shouldGenerateStructure": true,
	// Usually player spawn points are in a randomized area. With this enabled, players will always spawn in the middle of the structure (at the nearest air pocket).
	"forceExactSpawnMiddleStructure": true,
	// The y offset for the generated structure. Can for example be set to -1 if you notice a building always spawns one block too high.
	// min: -100, max: 100
	"generatedStructureYOffset": -8,
	// Prevents structures from being placed on top of trees. Any leaf and log blocks will be ignored during placement.
	"ignoreTreesDuringStructurePlacement": true,
	// Some schematic files might contain jigsaw or structure blocks. These are by default ignored during structure generation.
	"generationIgnoreJigsawAndStructureBlocks": true,
	// Whether the blocks from the generated structure should be protected from breaking/griefing.
	"protectStructureBlocks": false,
	// Whether entities spawned inside the generated structure should be protected from damage.
	"protectSpawnedEntities": true,
	// If enabled, players that are in creative mode will be able to break and place the structure blocks.
	"playersInCreativeModeIgnoreProtection": true,
	// If enabled, players that are in creative mode will be able to damage protected entities which spawned in structures.
	"playersInCreativeModeIgnoreEntityProtection": false,
	// If spawned entities inside the generated structure should not be allowed to move away from the block they spawned on. Disabled by default.
	"preventSpawnedEntityMovement": false,
	// Whether the initial world spawn point should be set to specific coordinates.
	"shouldSetSpawnPoint": true,
	// The new X coordinate of the spawn when shouldSetSpawnPoint is enabled.
	// min: -10000000, max: 10000000
	"spawnXCoordinate": 0,
	// The new Y coordinate of the spawn when shouldSetSpawnPoint is enabled. A value of -1 means on the surface.
	// min: -1, max: 10000
	"spawnYCoordinate": -1,
	// The new Z coordinate of the spawn when shouldSetSpawnPoint is enabled.
	// min: -10000000, max: 10000000
	"spawnZCoordinate": 0,
	// If entities from (structure block) schematic files should be spawned when found. These are entities not created with signs.
	"spawnNonSignEntitiesFromSupportedSchematics": true
}`

My starterstructere.json5. Set so the structure would spawn 8 blocks underneath the surface, only achievable while setting the spawn point, which is a shame because it would have been nice to also use Spawnbiome :)

**Comment by ricksouth** [comment]
Thanks! That'll help. I'll take a look soon :)

**Comment by ricksouth** [comment]
This has been fixed in version 3.1 of Starter Structure, with various new config options. With exact coordinates and offsets for both the player and the structure, it should be much more configurable. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/starter-structure/files
