### ISSUE TITLE
Infinite Trading Suggestion TradingAmountMultiplier/TradingCooldown

### ISSUE THREAD

**Issue by Wubzzz1337** [ricksouth/serilum-mc-mods#1631]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Infinite Trading

## **Feature description**
Have you thought about instead of just allowing unlimited trading to also allow us to maybe add some kind of "TradingAmountMultiplier: 2.5" so in that case you can trade 2.5x more times with any villager then Vanilla.

And maybe also
"TradingCooldown: 1800" so instead of the vanilla time it takes to restock you can choose the time in ticks it takes for the villager to get "restocked"

I know the name of the mod would then be kind of off, but hey, more options are always cool and I haven't seen any mod yet that has those option implemented.

Regards!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by redsamme** [comment]
A toggle/modifier for villager demand pressure could also be considered if implementing this suggestion
