### ISSUE TITLE
Mobs drop all items on all deaths, not just deaths by player

### ISSUE THREAD

**Issue by GamerPete** [ricksouth/serilum-mc-mods#1638]
## **Information**
Minecraft version: 1.19.3 / 1.20
Modloader: Forge / Fabric

Mod name: All Loot Drops

## **Feature description**
First, I must give my respects to your vast array of mods and your ability to keep up with their updates—well done! 

This mod is nearly the closest I've found to what I'm looking for. My goal is to have a mod that allows me to collect all available loot from mobs, even not by death by player. (Spiky Spikes would be great... if it were updated). My struggle is that I need to kill all mobs in my large mob farm in order to obtain the XP and full set of mob drops (emeralds from vindicators and evokers, as example); however, I cannot obtain those things unless I kill them myself. The requested iteration of this mod to allow its functionality to span across all deaths, allowing all available loot to be collected by methods other than specifically deaths by player. Outside of that, it is quite a useful mod!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
