### ISSUE TITLE
OmegaMute-Listen needs to be more fine tuned

### ISSUE THREAD

**Issue by menoobslayer** [ricksouth/serilum-mc-mods#1641]
## Listen mechanic is only semi effective.
Minecraft version: ALL
Modloader: Forge / Fabric.. Yes.

Mod name: OMEGA MUTE

## First off I would just like to say that in general this mod is a godsend, perhaps even the greatest mod in minecraft (mandatory as far as I am concerned).... BUT there is a pretty big issue when using listen in that it reports all sounds. Even muted ones.

In a low noise area this wouldn't be too big an issue perhaps, but in a noisy area the report text goes by so blistering fast that you can't read it. What is worse is that there is a limit to how much text will be logged so it is genuinely hard to identify a annoying (but limited occurrence) sound surrounded by overwhelmingly repeated sounds.

Here is a specific example; I have an automatic chicken farm with a few hundred chickens close to my villager area and my cow/sheep/pig entity cram spots are also close. I can hear another annoying noise right there but can't see it in the log at all because of how much muted sound is being reported.

The sound in question is a minecart going around. I have searched mine, cart, roll, track, rail.... CANNOT FIND THE SOUND STILL... ARRGAHRHSGSDGASDG

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I've added some new features to Omega Mute in version 4.0. It also improves the '/omegamute listen' command to only show new sounds once. You can still have the old functionality by using '/omegamute listen all'.

https://curseforge.com/minecraft/mc-mods/omega-mute/files
