### ISSUE TITLE
Decrease diamond and emerald drop chances in Mineral chance or add emerald/diamond counterparts for nuggets

### ISSUE THREAD

**Issue by malomaster** [ricksouth/serilum-mc-mods#1649]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge

Mod name: **Mineral chance**

## **Feature description**
**Can you decrease drop chances for emeralds and diamonds? Or can you add to this mod something like iron & gold nuggets, but for diamonds/emeralds like "Diamond shard" or something?**
The idea of getting sometimes valuable resources from just digging dirt or mining stone very motivate to digging more. But sometimes this mod became to OP.
I think you remember Quarry from "Industrial craft 2" in MC 1.12.2. For newer MC versions there are mods like updated "QuarryPlus" (called "Enchanted miner"). The point is, when using these mods, IDK is this a bug or a feature, but I think quarry machine works like player, because mineral chances works for it, so it also got additional minerals. And if getting near 500 gold and iron nuggets from digging down to bedrock by default Coal miner is not so much, the same for lazuli/redstone, but ≈500 emeralds and diamonds from the same quarry I think is too much OP.

Because of this I suggest 3 options:
1. Just decrease diamond/emerald chances at least 5 times (maybe even 10 times for better balance). I think, it will be the easiest way, but the problem is player will also get 5(10) times lesser emeralds/diamonds from mining by pickaxe, so it became boring.
2. Somehow find a way to differentiate mining by player and mining by machines like miners from QuarryPlus and significantly decrease chance of getting additional minerals (or, if possible, only emeralds/diamonds) or even turn off this feature (NOT recommended, because it is also too boring) for machines.
3. Add to your mod emerald and diamond counterparts for gold/iron nuggets, so player will get them instead of full emeralds/diamonds. In this case mod became more balanced and mining by machines will not be too OP.

Also is it possible to somehow add some modded ores/minerals/gems from other mods to the "Mineral chance" drop list?
Also can you make the possibility to change drop rate for every mineral in list manually in the config file? Of course, if it doesn't require rewriting a large chunk of the mod's code.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
