### ISSUE TITLE
Followers Teleport Too - Xaeros-minimap Waypoint support?

### ISSUE THREAD

**Issue by akharding91** [ricksouth/serilum-mc-mods#1651]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 43.2.4

Mod versions installed: Followers Teleport Too 1.19.2-2.1 & Xaeros_Minimap_23.1.0_Forge_1.19.2

## **Feature description**
I was wondering if you could add support for [Xaeros-minimap](https://beta.curseforge.com/minecraft/mc-mods/xaeros-minimap) waypoints? I believe they use the /tp command when their waypoints are used. Its not causing a crash or anything, just the two mods dont seem to work together, i use the Xaeros-minimap waypoints to teleport & my pet get left behind is all.

Edit: added photo
![2023-02-28_03 47 27](https://user-images.githubusercontent.com/29419588/221846176-3134211e-44d6-43a8-9d06-e073dc223988.png)

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
