### ISSUE TITLE
[Question/Request] Can we mute conditionally?

### ISSUE THREAD

**Issue by DemonSlayer112** [ricksouth/serilum-mc-mods#1655]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.14
Environment: Singleplayer

Mod name: [Omega Mute](https://www.curseforge.com/minecraft/mc-mods/omega-mute)
Mod version: 3.0

## **Question**
Are we able to mute specific mobs conditionally?
Im asking for minecarts, specificly mobs _in_ minecart, like if theres a mob in a minecart, mute it.
Can we do this? And could something like this be added if not?
Would be great for trading halls for zombie and or villagers in carts most the time.

**Comment by ricksouth** [comment]
That's unfortunately not possible. The mod uses the sound name to determine if it should be muted. Since Minecraft doesn't have a different sound for a cart that's occupied, I can't differentiate between them without doing expensive processing checks. Appreciate the interest though and thanks for giving the mod a try!
