### ISSUE TITLE
Hide Hands mod additional functionality

### ISSUE THREAD

**Issue by menoobslayer** [ricksouth/serilum-mc-mods#1659]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod name: Hide Hands

## **Hide equipped unless in use**
By default the mod has the option to hide main/off hand 100% of the time or to blacklist specific items... Additionally it will always hide an empty hand unless being swung.

The thing I am focusing on is that you can hide the hands while not in use but show them while you are swinging them. This is exactly what I would like but for equipped items. AKA I don't need to see a weapon/tool 100% of the time, but seeing it while swinging it is helpful/immersive.
Even more notable then that is a shield for example, which takes up a huge amount of the screen, I don't need to see that ALL the time, but conversely not being able to visibly tell that my shield is raised(100% off) is weird.
So ya, give an option to have main/offhand flexibly display like empty hands please!

I expect this change would really only end up using the already existing code and would really flesh out the functionality of the mod.

**Comment by ricksouth** [comment]
I can see the appeal of doing it for all tools. Thanks for the suggestion!

As for hiding the shield, this exists in the following mod already:
https://www.curseforge.com/minecraft/mc-mods/passive-shield

**Comment by menoobslayer** [comment]
NP, more then that thank you for the quick reply and suggestion to hide the shield. Your consideration is really appreciated!

Since you seem to be onboard with the concept, any idea of what an ETA for the update might be like? Not trying to be pushy, I know that different people have different priorities and you may be busy with other projects or RL etc.

**Comment by ricksouth** [comment]
Difficult to say. Bug reports have priority, and there are a lot of open feature requests already. I try to get to them all in time, but there's a lot.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
