### ISSUE TITLE
Blacklist for Double Doors

### ISSUE THREAD

**Issue by Kasprenius** [ricksouth/serilum-mc-mods#1675]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric

Mod name: Double Doors

## **Feature description**
I would love it if you could add a blacklist to the Double Doors config! I have a special type of door that opens normally from the front but can't be opened from the back without redstone but this mod ignores that and lets you open 2 of them from any direction and doesn't play the door sound XD. So I'd love to be able to just opt out this specific type of door without losing the mod

**Comment by tobi-blackscale** [comment]
This would be really useful, to gain more compatibility, without needing specific code for each and every door mod out there. 
To give another example: The sliding doors from create. They already open as double doors, but when double doors is active and used they slide and open like regular doors at the same time.

![grafik](https://github.com/ricksouth/serilum-mc-mods/assets/71216944/44be40c9-7098-4a98-b227-482b92a48870)

**Comment by Xephorian** [comment]
I would second this for the same reason, or just the ability to Bind a key to disable the function altogether. In the mod description it says crouching will disable the double door feature, but this doesn't work with trapdoors since crouching prevents you from interacting with trapdoors at all

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
