### ISSUE TITLE
Quick Paths should prioritise paths which keep the same elevation

### ISSUE THREAD

**Issue by Jameskmonger** [ricksouth/serilum-mc-mods#1679]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge

Mod name: Quick Paths

## **Feature description**
I would like paths created by Quick Paths to remain at the same elevation where possible. Often the pathfinder will cut corners to take a "shorter" path, but one which involves jumping down and then back up again.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by Jameskmonger** [comment]
@ricksouth I'm happy to raise a PR for this if you can point me in the right direction :)

**Comment by ricksouth** [comment]
If you want to give it a whirl, sure! :)

The source code is available here:
https://github.com/Serilum/Quick-Paths

Should be as simple as loading up the module into IntelliJ.

The wiki page is still a work in progress, but make sure to add these exclusion settings:
https://github.com/Serilum/.information/wiki/Pull-Request-Information

That's needed because of the way I merge the mod loaders. Everything should work normally on the dev environment otherwise. Appreciate it!

**Comment by ricksouth** [comment]
If you want to give it a whirl, sure! :)

The source code is available here:
https://github.com/Serilum/Quick-Paths

Should be as simple as loading up the module into IntelliJ.

The wiki page is still a work in progress, but make sure to add these exclusion settings:
https://github.com/Serilum/.information/wiki/Pull-Request-Information

That's needed because of the way I merge the mod loaders. Everything should work normally on the dev environment otherwise :)

**Comment by ricksouth** [comment]
Make sure to choose one of the versions I'm still actively developing. Hopefully that's ok.

Currently: 1.19.2, 1.20.1, 1.20.2 and 1.20.4.

If you make the code work for one of those, I can easily add it to the rest.
