### ISSUE TITLE
Treehavester time to harvest calculation

### ISSUE THREAD

**Issue by KostromDan** [ricksouth/serilum-mc-mods#1680]
Add option in cfg LogsCountCalculator = "LogCount" by default
Also where should be option "Radius", this means that mod will calculate log count by only harvesting level of tree:
![image](https://user-images.githubusercontent.com/90044015/226749193-8236237d-c2f3-4b3c-a3a1-ce864ae1bcdc.png)
Its more logical and realistic.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
