### ISSUE TITLE
(Giant Spawn) Nerf the melee range & health on giants

### ISSUE THREAD

**Issue by riley-9054** [ricksouth/serilum-mc-mods#1702]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Giant Spawn

## **Feature description**
Nerf the melee range on the giants because it's a nightmare to try and get close enough to them to get melee hits in, and their melee range currently feels more like they're telepathically hurting me than actually physically attacking.
Nerf the health of giants because currently it feels a bit too tedious to kill them, though I am saying that while I've only ever killed them with a crossbow due to the aforementioned melee range issue.
Also maybe give them zombie sounds that are played with the pitch reduced, and if possible it'd be nice to see baby giants added to the mod since they existed in the 18w50a snapshot. Though I'd suggest giving the babies even less health, melee range, and damage than the adult versions, since baby zombies having the same stats as adult zombies is enough of a problem and would just be made worse with giants.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
