### ISSUE TITLE
[Starterkit] Add a command to obtain the starter kit again

### ISSUE THREAD

**Issue by Martmists-GH** [ricksouth/serilum-mc-mods#1711]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric

Mod name: Starterkit

## **Feature description**
I'm using the starter kit to provide the player with a guidebook, but if the player uses this, there's no easy way to obtain another one as the /starterkit command does not have a way to provide these items, and I can't use custom crafting recipes in a datapack as there's no way to attach NBT to a crafting result.

As such, it would be great to allow users to use some subcommand of /starterkit to obtain the items again.

**Comment by James103** [comment]
See also https://github.com/ricksouth/serilum-mc-mods/issues/743

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thank you again for the feature request!

I've been working hard on lots of new features for Starter Kit these past few days. Version 6.0 is now available on CurseForge and Modrinth. It contains many new features, and this one has been added too :) Hope you enjoy them!

https://legacy.curseforge.com/minecraft/mc-mods/starter-kit
