### ISSUE TITLE
Tree harvester - treeHarvestWithoutSneak": false  doesn't apply to Operators

### ISSUE THREAD

**Issue by C4uTi0N** [ricksouth/serilum-mc-mods#1752]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.19.4-8.0

## **Description**
The option "treeHarvestWithoutSneak": false" doesnt apply to Operators

Before Holding sneak button the option does apply.
After cutting down one tree while holding sneak, the option doesn't apply anymore
(entire tree falls without holding sneak)

**Comment by matzar24h** [comment]
1) Also encountered this on forge now, I have settings for harvesting with sneak. When during breaking block i press sneak after start of block breaking, tree harvest very fast, and from now on, every tree is harvested without sneak. Setting doesnt work properly anymore. Also calculations doesnt work anymore, it's just harvest whole tree with time of breaking only 1 block.
Edit: Version 7.2 works fine. Today is the first day I use this mod, so version 8.0 on 1.19.2 was bugged. 

2) Also I encountered kinda exploit for insta harvest.  On 7.2, dont know if it's on 8.0.
Look up on screenshot, when I will break this block seperated by sides, only is touching in diagonals it'll insta harvest tree without calculated time breaking. 
![2023-05-11_16 48 16](https://github.com/ricksouth/serilum-mc-mods/assets/132963188/07d8a90b-0977-4623-892a-b279afef7cc3)

3) It would be nice if hotkey for harvesting tree would be configurable, instead of only shift/no-shift setting.

4) I'm very happy normal/diagonal/shift/no-shift chopping doesnt affect logs placed by player. :)

5) Fifth thread of my writing is about big assed tree stopped completely entities, 
is there a way to chop down this with this mod?
![2023-05-11_19 09 36](https://github.com/ricksouth/serilum-mc-mods/assets/132963188/c54a3afa-dc6d-444b-8912-6ffbea3c3205)

**Comment by ghost** [comment]
In singleplayer no matter if i sneak or not it harvest the entire tree. But if i hold shift, it switch to being slower.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
