### ISSUE TITLE
Villager GUI Lacks Localisation

### ISSUE THREAD

**Issue by Laton95** [ricksouth/serilum-mc-mods#1762]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.6
Environment: Singleplayer

Mod name: Villager Names
Mod version: 1.19.2-5.2

## **Description**
Profession names in the villager GUI pull directly from the registry names, but don't replace underscores with spaces. While this isn't a problem in vanilla, this leads to unlocalised looking text with some modded professions. The villager GUI is also unable to be translated in general due to hardcoded strings. Either replacing underscores or implementing full localisation would be nice.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
