### ISSUE TITLE
Add effect on first server join for a x amount of time [Fabric 1.19.2]

### ISSUE THREAD

**Issue by xR4YM0ND** [ricksouth/serilum-mc-mods#1779]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric

Mod name: Starter Kit

## **Feature description**
Would be awesome to have extra effect lines in the config to add minecraft or other mods effects to new players for a certain amount of time (eg. Comfort Effect from Farmers Delight for ~ 20min)

We would use this in our Aged Modpack running Fabric 1.19.2

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thank you again for the feature request!

I've been working hard on lots of new features for Starter Kit these past few days. Version 6.0 is now available on CurseForge and Modrinth. It contains many new features, and this one has been added too :) Hope you enjoy them!

https://legacy.curseforge.com/minecraft/mc-mods/starter-kit
