### ISSUE TITLE
Apply passive shield defense buff to non-player mobs

### ISSUE THREAD

**Issue by KateYagi** [ricksouth/serilum-mc-mods#1795]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod name: Passive Shield

## **Feature description**
Context: 
I have been playing with Dungeon Crawl recently, which spawns many zombies and skeletons that have shields. These seem to be for show and loot only though, and I wanted to use this mod to make them tougher, but reading the mod description's exclusive reference to players holding shields--and the code itself, it seems to only effect players.

Features Requested:
- Apply same damage reduction this mod applies to players holding shields to apply to other mobs that can hold shields. 
- A separate configuration parameter for the reduction applied to mobs holding shields, since they cannot raise their shields like players can, so it would be fair to give them a larger buff.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
