### ISSUE TITLE
Blacklist certain areas for Tree Harvester functionality

### ISSUE THREAD

**Issue by tompo-live** [ricksouth/serilum-mc-mods#1797]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.19.3

## **Description**
Quickly harvesting trees is a life saver. However, when my friend was building a massive tree for a base, added leaves and then it all fell down. Obviously spending 2 hours harvesting logs and building just for it to all fall down is horrible.

![2023-05-28_02](https://github.com/ricksouth/serilum-mc-mods/assets/135545812/7df72f34-5bdd-40d0-8e5b-37ccd7227c62)

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
I'm sorry that happened. This is unfortunately not considered a bug though, since the mod works with modded trees. They can have a shape similar to that, and thus the mod works with cutting it down. I can leave this open as a feature request to somehow blacklist areas where the mod works. But not sure how that would work out yet.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
