### ISSUE TITLE
[Suggestion][Villager Names] Allow the sufixes to be translated

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#1804]
## **Information**
Minecraft version: 1.20
Modloader: Fabric

Mod name: Villager Names

## **Feature description**
Basically, allow the profession sufixes (eg.: <name> the Librarian, <name> the Farmer) to be translated using resource packs to further immersion for non-English players.

**Comment by yermachello** [comment]
Also would be cool to be able to turn it off in the config completely, since for example in russian the line could get too big to fit the GUI

**Comment by Wani4ka** [comment]
I've made a fork of this mod and implemented this feature, but [the mod license](https://github.com/ricksouth/serilum-mc-mod-sources/blob/main/sources/Villager%20Names/1.19.2/LICENSE.md) doesn't allow distributing it [without permission](https://github.com/ricksouth/serilum-mc-mod-sources/blob/main/sources/Villager%20Names/1.19.2/note-from-author-villager-names-source.txt). I'm waiting for the mod author to reply to my DM on CurseForge so that I could publish this fork and make a pull request for original project.

Here are changes of this fork:
* Merchant menu title can be modified as you want using localization key `gui.merchant.title`, which is `%1$s the %2$s` by default (`%1$s` is replaced with the villager's name, and `%2$s` is replaced with the villager's profession)
* Villager level can be hidden from merchant menu title, using a new configuration parameter called `showVillagerLevel`

![image](https://github.com/ricksouth/serilum-mc-mods/assets/31739611/2f12afdf-1a19-4d75-90e7-28cdab29d40f)
On the screenshot above, merchant menu title format is `%1$s a %2$s` instead of "the" variant.

![image](https://github.com/ricksouth/serilum-mc-mods/assets/31739611/c983a3d0-fd0e-4b9d-8b7d-af75313fc015)
On the screenshot above, the game is in Russian, and merchant menu title format is `%2$s %1$s`.

![image](https://github.com/ricksouth/serilum-mc-mods/assets/31739611/d7129cac-ecf2-490b-b87e-cbf636fd2254)
On the screenshot above, the game is in Russian, merchant menu title format is `%2$s %1$s`, and villager level is shown.

**Comment by vico93** [comment]
Yeah, its a shame that his mods arent open source. FOSS mods can be quickly updated by others if the author can't do it for a while, plus that allow others to port to versions/platforms that the author dont have the resources to work with.

**Comment by Wani4ka** [comment]
4 months later =/////////

I'm totally shocked at how much the author of the mod doesn't care about feature requests, yet he finds the time to update all his mods to new versions, and to make it difficult to rebuild them. I don't need donations,, I just need this feature. Therefore I made my own version of the mod, in which I re-implemented villager naming feature and optimized it.

You can [email me](mailto:l87hxgfg@duck.com?subject=Villager%20Names%20mod%20request) so I can send you this mod. As of now, it only works on Fabric 1.20.1 and doesn't support modded villagers. I plan to add support for more game versions and mods, but not now. That's why I don't want to publish it yet.

If you are using custom villager names, please also send `customnames.txt` so I can help you convert it to the new format.

**Comment by ricksouth** [comment]
@Wani4ka It's not surprising that life gets in the way sometimes. My mods are available for free and sometimes I won't have time for working through the issues on Github. I find it a bit rude that you're "shocked". But understand that you'd like to have things implemented faster.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
