### ISSUE TITLE
Disable TNT Breaks Bedrock in Overworld Option

### ISSUE THREAD

**Issue by ringprod** [ricksouth/serilum-mc-mods#1814]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: TNT Breaks Bedrock

## **Feature description**
You should add the ability to disable bedrock from breaking in the overworld through a menu option or gamerule. The primary situation where you would want to break bedrock would be to get on the nether roof, so this option should be disabled by default.

**Comment by ReusableKey** [comment]
You can just disable the mod yourself when you dont want bedrock broken. its a lot easier to do it like that than to write the code for it

**Comment by ringprod** [comment]
No, I mean I would like the ability to mine with TNT in the overworld without fear of destroying the bedrock, but maintain the ability of breaking blocks in the nether for roof access.

**Comment by ReusableKey** [comment]
i get that but i mean whenever you plan to break nether roof put the mod in your mod folder and once your done quit the game take it out and restart. its a very minor inconvenience for you sure, but how often do you really break up the Nether roof and TNT mine in the overworld in the same session? im sure its not very often

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
