### ISSUE TITLE
[FR] Tree attachments such as fruit trees and [FR] shears such as with vines

### ISSUE THREAD

**Issue by skaviouz** [ricksouth/serilum-mc-mods#1828]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod Tree Harvester

## **Feature description**
Some trees have attachments. In vanilla, the fact you destroy the supporting block destroys the tile entity such as vines or cocoa beans.

However, there are custom attachments added by some mods, such as "Pam's Harvestcraft 2 - Trees" with it's fruit trees. Even if you don't want to do all that extra work to find item ids or what not, if there was an option in the config that allowed adding "pamhc2trees:*" or any other specified/wildcard to just harvest when within a block distance of any harvested wood or leaf that would be appreciated.

I have a second request, if you have shears in your inventory, you can shear vines attached to the tree for as much durability you have on the shears while the rest is "destroyed" normally. This could also be a second config option, so if someone wants to enable shearing of leaves with the tree harvester, they can just add "*leaves" or "minecraft:*leaves" to this config option.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
