### ISSUE TITLE
Additional recipe(s) for Furnace Recycle

### ISSUE THREAD

**Issue by WilliamBlaze** [ricksouth/serilum-mc-mods#1829]
Mod: Furnace Recycle

-- Well originally I had forgotten all about Vanilla minecraft allowing your to smelt down iron and gold armor and gear into iron and gold nuggets, and I was going to suggest adding that (which honestly those recipes could be improved a bit) but! That wasn't the only part of the entire idea, so I still have something worth submitting.

"Being able to smelt down a Lightning rod or Spyglass back into a copper ingot."
Pretty simple and straight forward, and still fits the vanilla theme of the existing recipes already added by this mod without losing it's well balanced feel.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
