### ISSUE TITLE
Add a config so that player heads only drop when the player is killed by another player.

### ISSUE THREAD

**Issue by K4LCIFER** [ricksouth/serilum-mc-mods#1853]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Just Player Heads

## **Feature description**
Currently the mod seems to only drop player heads when the player dies, but it would be also nice to have the option so that the playerhead drops only when killed by another player.

As a side note, it may also be nice to add a config option so that the player head drops by a charged creeper.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by RubyRezal** [comment]
I would like to second this request.  The requested feature "Only Drop Heads By Player Kill" is an option in Just Mob Heads. It should be an option for Just Player Heads as well.

It's actually a bit inconvenient for player heads to drop from every player death. However, reducing the drop chance would cause issues with player kills with the intent of collecting heads (i.e. PvP, shooting arrows up and "catching" them)
This option would help reduce unwanted inventory clutter by only dropping a player head when a player head drop is intended and appropriate.
