### ISSUE TITLE
The Vanilla Experience (Mod) for fabric, and minecraft 1.20.1?

### ISSUE THREAD

**Issue by Therkelsen** [ricksouth/serilum-mc-mods#1857]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21

Mod name: The Vanilla Experience (Mod) (Forge)

## **Question**
Hey!

I was wondering if [The Vanilla Experience](https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience) is avaliable for Fabric, for Minecraft 1.20.1?

**Comment by EightBitBBQ** [comment]
Yes its available for Fabric.
The modpack is enrolled with Forge as a standard. But if you put in the Fabric API and launcher you should have no issues (using it myself).

Serilum's mods are compatible both ways

**Comment by EightBitBBQ** [comment]
Sorry! Mis understood / read the question.
No the mod wont be updated. But the Modpack should work

**Comment by Therkelsen** [comment]
How come? :D

**Comment by EightBitBBQ** [comment]
Hard to say on my end. The complete Experience is more like a Modpack.
So, this way more options with settings / configs.
Also not all people want all options.

So the Experience is more configurable to a persons interests

**Comment by Therkelsen** [comment]
Sure, makes sense. It would just make maintenance of my pack easier, if it existed for 1.20.1 and Fabric :D

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
