### ISSUE TITLE
Better Better Bees

### ISSUE THREAD

**Issue by YumatanGames** [ricksouth/serilum-mc-mods#1879]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge / Fabric

Mod name: Realistic Bees

## **Feature description**
Hi,

I'm a fan of your Realistic Bees mod and have a suggestion for an enhancement. I came across an abandoned mod, Brainier Bees, which had a feature where bees remember their hive and don't get lost. I think a similar feature could be a great addition to Realistic Bees, with some modifications to avoid complexity or lag:

1. Bees remember their hive.
2. Bees don't fly too far from their hive.
3. Bees teleport back to their hive when stuck or when fail to pathfind back for any reason.

I also have a suggestion for a feature that allows players to change the hive in a bee's memory:

1. Find a bee nest/hive with bees.
2. Place a new hive/nest within 30 blocks.
3. Place a Campfire under the old hive/nest.
4. Attract the bees out by right-clicking with a flower the old hive/nest and lead them to the new hive.
5. Right-click with the flower on the new hive. Bees following the player will take it as their new home. If the new hive is full, the remaining bees will revert to their normal behavior.

Lastly, bees without a hive/nest could have a chance to spawn a new nest under certain conditions:

1. Around 60 blocks of a flower.
2. At least 3 blocks above ground.
3. On a stone or wood block, including variants.

I believe these changes would make the bees' behavior more realistic and engaging. I hope you find these suggestions useful and look forward to seeing how Realistic Bees evolves.

Thanks for your time and great work!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
