### ISSUE TITLE
Configurable Extra Mob Drops- Adding drops using command blocks using item id rather than holding it

### ISSUE THREAD

**Issue by LILL097** [ricksouth/serilum-mc-mods#1896]
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Configurable Extra Mob Drops

The mod by now allows you to add a custom drop by holding a certain item in your main hand. What i would like, is to be able to ran a command block using a command such as "/cemd adddrop minecraft:dirt minecraft:zombie" (using ids also for the entity would be better to specify which entity and have less conflicts between mods). This would allow modpack makers to use the command as a quest reward for ftb quests: you complete a certain quest => a mob starts dropping what you want.
I am currently working on a modpack and i'm really looking for this kind of stuff and your mod seemed to be the only one getting close to it

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
