### ISSUE TITLE
Brightness always goes back to 50%...

### ISSUE THREAD

**Issue by Stephen5311** [ricksouth/serilum-mc-mods#1898]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Full Brightness Toggle

## **Feature description**
When you close the game and relaunch, the full brightness always goes back to 50% brightness by default. This is very annoying to always have to go in the options menu and switch it to 100% again. Could you make it so it remembers/saves the brightness value it had between launches; or just make a config where you can type the percentage you want the brightness to default back to?

Thanks for this amazing mod!
~Stephen5311

**Comment by James103** [comment]
This is caused by the brightness value (with the mod on) being greater than 100% or less than 0%.
Due to changes made in Minecraft version 1.19, when the brightness value is outside vanilla bounds (as is the case with the mod active), a value of 50% gets saved to the options file, regardless of the actual value.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Full Brightness Toggle version 4.0 has the fullbright state persistent across game launches. So it'll remember if it was on/off and keep it that way.

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle/files

**Comment by BibiBaggins** [comment]
so im guessing the stuck on 50% when fullbright is turned off cant be solved then???
