### ISSUE TITLE
GUI Compass/Clock toggles

### ISSUE THREAD

**Issue by Maccchus** [ricksouth/serilum-mc-mods#1908]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge

Mod name: GUI clock/compass

## **Feature description**
the GUI Clock mod has the "showOnlyMinecraftClockIcon" which is the mode but this means that it hides the number of days played too and i would love to have an option to see both at the same time.
the GUI Compass on the other hand does not have a similar option to show the actual compass in the GUI. While its not exactly as practical as the GUI clock, a toggle like this would be nice rp-wise (+ it would fit perfectly with the Northern Compass mod).

On a different topic, it would also be nice to add compatibility to curio slots. I tried adding them to belt slots but they dont show up in the GUI anymore.

That is all and thanks for all your lovely qol mods! they are essential to every version that i play :D

**Comment by rckymtnrfc** [comment]
Curios slots pretty please!

**Comment by PlayfulPiano** [comment]
also voicing support for curios slots and functionality for gui compass/clock

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
