### ISSUE TITLE
Wool Tweaks support for modded wool-based blocks?

### ISSUE THREAD

**Issue by Gamemassa** [ricksouth/serilum-mc-mods#1926]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge / Fabric
Mod name: Wool Tweaks

## **Feature description**
There are a handful of mods that add wool doors, stairs, slabs, pressure plates, fences walls, buttons and other stuff, and I was just curious if it'd be possible to add Wool Tweaks support for some of these. The ones I use in my Forge and Fabric custom modpacks are listed below:

Fabric:
- [More Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/more-decorative-blocks-blackwolf-design)
- [Blockus](https://www.curseforge.com/minecraft/mc-mods/blockus)
- [Extended Block Shapes](https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes)

Forge
- [More Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/more-decorative-blocks-blackwolf-design)
- [Material Elements Panels Plates and Slabs](https://www.curseforge.com/minecraft/mc-mods/material-elements-panels-plates-slabs)

**Comment by Gamemassa** [comment]
@ricksouth I notice it says "Mod Label Missing" above. I'm not sure if the mod label is something I was supposed to assign when I made this post, but it's supposed to be Wool Tweaks.

**Comment by Gamemassa** [comment]
@ricksouth Hi, just wondering if I could get a response.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
