### ISSUE TITLE
Pulling Collective's hard-coded GlobalVariables into a JSON

### ISSUE THREAD

**Issue by SeymourGx** [ricksouth/serilum-mc-mods#1949]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Collective

## **Feature description**
Given how obviously central Collective is, I don't know if this is ever feasibly changeable without updating each and every Serilum mod, but it would be nice if:

1. The GlobalVariables.java file had some or all of its contents pulled into a JSON or similar filetype for end-user editing, or
2. The mods that implement those variables allowing for some tweaking on their end.

I've tried to dive into multiple Serilum mods we're using, i.e., Villager Names and Random Village Names, to add some custom names for humorous or nostalgic reasons. I then found that the names are hard-baked into a .class file within Collective's .jar, rendering this feat impossible (AFAIK) without compiling modified source code. Storing these sets of text data in a data-friendly filetype as opposed to source code would allow for greater end-user customization of Serilum mods or even allowing other mods or scripts to hook in and do the same. Again, perhaps an impossibly heavy lift, but I thought worth mentioning. Thanks!

**Comment by ricksouth** [comment]
This is definitely something that I'd like to do. Possibly even generate those files only if the dependent mods are present. Not sure when I get to it, but thank you for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
