### ISSUE TITLE
[Tree Harvester] Wooden Axe Balance

### ISSUE THREAD

**Issue by ConqAra** [ricksouth/serilum-mc-mods#1953]
Minecraft version: 1.18.2
Modloader: Fabric
Mod: Tree Harvester

Balance tree harvester, make it so wooden axes cant take down an entire tree. The reason is you can get away with using a wooden axe and even if it breaks when mining a giant tree, it will still get the job done. Just seems a little redundant in mining trees with your GOOD axes besides speed. "Why would I waste durability on my iron or diamond axe when I can just sacrifice my wooden or stone one". There's no repercussions such as not being able to chop the whole tree down for using a bad axe. 

Maybe not only have it calculate the durability the axe would take, but stop the tree harvesting at the specific log point where the axe wouldn't be able to chop it down anymore. i.e. a jungle tree is only half harvested because the wooden axe is too weak to break down all of it.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
