### ISSUE TITLE
config for milk all the mobs

### ISSUE THREAD

**Issue by UomoNormale4** [ricksouth/serilum-mc-mods#1955]
Mod name: Milk All the Mobs

I don't know how difficult it would be, and it's a bit of an odd request. But perhaps a config? A list you can add mobs to in order for it to work on them as well. (like if someone was doing a nether survival, they could make hoglins milkable to help combat the withering effect. Or if someone wanted to add a modded mob to the list, or remove one that's already in it)
though idk how you've got the mod set up/coded, so this may be impossible. But if possible, it would be quite handy and very adaptable.

my bad for the lack of a proper mod label, as i don't rightly know how to add that

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by matzar24** [comment]
I would change name of this mod on "Milk me!" xD
