### ISSUE TITLE
[Feature Request] Spiders Produce Webs - Tracking Requirement Toggle

### ISSUE THREAD

**Issue by PlayfulPiano** [ricksouth/serilum-mc-mods#1999]
## **Information**
Minecraft version: 1.18.2 (Realistically all maintained versions)
Modloader: Forge / Fabric

Mod name: Spiders Produce Webs

## **Feature description**

Basically, this suggestion is to add a toggle in which a spider is unable to produce cobwebs if it is unable to reach the player from its current position. This is mainly to prevent the mod from having the potential to break mob spawner spider farms, if the player decides to decrease the tick rate for this mod to something much more frequent.

For example, if a spider can track a path where they can reach the player without obstruction, then cobwebs can be generated. Otherwise, even if they're able to move (i.e. climb walls), they cannot generate cobwebs.

I'm pretty sure the mod "Peeping Creepers" has this sort of behavior configured when it comes to creepers being able to breach through walls or not, although I'm not 100% sure.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
