### ISSUE TITLE
[Villager Names] name opacity

### ISSUE THREAD

**Issue by Nycto97** [ricksouth/serilum-mc-mods#2003]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.2
Environment: Multiplayer

Mod name: Villager Names
Mod version: 5.2

## **Question**
I installed the mod Merchant Markers and noticed that compared to the Villager Names, the opacity of the merchant icons is bright.
In their config, there's a setting to adjust the opacity of the icons.

In this image, the opacity is set to 0.6, while also being night.
![image](https://github.com/ricksouth/serilum-mc-mods/assets/83367226/6d63fdd4-1703-45ee-b871-c15f8e5ca220)

In this image, the opacity is set to 0.6, while being day.
![image](https://github.com/ricksouth/serilum-mc-mods/assets/83367226/f10e9cc9-327c-4072-91f3-4b17d440f9a0)

Now, what I can do is lower the opacity even more to get it matched with the villager names, but I was wondering, isn't it possible to raise the brightness/opacity of the Villager Names instead?

I also noticed that when it's night, the villager names are less bright, which I really like btw, but is there a way to increase the brightness/opacity of the Villager Names?

Kind regards,
Nycto

**Comment by Nycto97** [comment]
Found out this is related to shaders:
- Shader on: lower brightness on name tags + higher brightness on icons from Merchant Markers
- Shader off: higher brightness on name tags + lower brightness on icons from Merchant Markers

Shader used: Complementary Reimagined v5.0.1

Shader on:
![2023-10-20_04 27 45](https://github.com/ricksouth/serilum-mc-mods/assets/83367226/a2ba5af7-2491-4758-acb4-9e2e6ba3b0ed)

Shader off:
![2023-10-20_04 27 27](https://github.com/ricksouth/serilum-mc-mods/assets/83367226/f3587314-f520-4870-a426-fb223c81656e)

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
