### ISSUE TITLE
[Areas] Teleporting message

### ISSUE THREAD

**Issue by Spazer-Prime** [ricksouth/serilum-mc-mods#2007]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge / Fabric

Mod name: Areas

## **Feature description**
When teleporting out of a place with an Areas sign, the "The area [name] no longer exists" message pops up like the sign was destroyed. I'm not sure if there's really anything to be done about it, but I thought I'd submit a feature request (I didn't think it was a bug) as it would be nice to use Waystones without it popping up when I leave home. Thanks for so many awesome mods btw!
![2023-10-23_22 50 39](https://github.com/ricksouth/serilum-mc-mods/assets/146499778/09be4ea0-474b-4408-8709-f1f463ac8184)

**Comment by EasternGamer** [comment]
Had the same issue, should super simple to fix. It's simply saying that if the radius exceeds the radius of the zone, and it is not a leaving message, do not send a message.
I may do a pull request, but I'm not sure how that will work with the way they've done it with this repo since all the mods are in one place, and there are like zero pull requests done.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 5.4 of Areas.

https://curseforge.com/minecraft/mc-mods/areas/files
