### ISSUE TITLE
All villagers have the same 3 names

### ISSUE THREAD

**Issue by HatTrkPatrk** [ricksouth/serilum-mc-mods#2031]
## **Information**
Minecraft version: 1.20.2
Modloader: Fabric
Fabric loader version: 0.14.24
Environment: Multiplayer

Mod name: Villager Names
Mod version: 6.1

## **Description**
All the villagers in my world are being created with the same 3 names, Rick, Bob, and Eve.

## **Crash report**

villagernames.json5
https://gist.github.com/hattrickpatrick/4d9bc6e799bc6fbdceec928c1ba4dc2e

villagernames/customnames.txt
https://gist.github.com/hattrickpatrick/2a8064e02130dcef108813ae7eecf87c

![image](https://github.com/ricksouth/serilum-mc-mods/assets/5185596/909e5566-52df-4502-8e59-983e4e11991a)

**Comment by ricksouth** [comment]
Thank you for opening the issue. I did attempt to prevent this, but apparently it didn't load correctly for your world. Apologies for the inconvenience. The latest update detects and removes the old default custom names list correctly. Fixed in version 6.4 of Villager Names.

https://curseforge.com/minecraft/mc-mods/villager-names/files
