### ISSUE TITLE
Persistent Inventory Search be able to know where the sidebar was

### ISSUE THREAD

**Issue by peow** [ricksouth/serilum-mc-mods#2050]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Persistent Inventory Search

## **Feature description**
when I close the inventory and open it again, the scrollbar goes up by itself

![image](https://github.com/ricksouth/serilum-mc-mods/assets/105888751/afb35283-0340-4f63-abb9-34ba982fccfb)

after reopening:
![image](https://github.com/ricksouth/serilum-mc-mods/assets/105888751/ea0895bf-2e3f-44e0-97b8-ef8b66af7586)

it would be interesting if your mod kept the scrollbar where i left it
if you gonna accept this suggestion pls make an update to fabric 1.20.1

**Comment by peow** [comment]
it would also be interesting if the ModMenu search bar was also affected by these things, it would help a lot when configuring modpacks

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
