### ISSUE TITLE
Suggestion: Configurable Despawn Timer - Item Protection/Invincibility Toggle

### ISSUE THREAD

**Issue by TBlazeWarriorT** [ricksouth/serilum-mc-mods#2060]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge

Mod name: Configurable Despawn Timer

## **Feature description**
Simple Suggestion: Could you please make a toggle so that alongside with making items not despawn, they also get protected? (from explosions, lava, etc)
Advanced Suggestion: I would appreciate another toggle for void protection, that teleports items that reach the void to the nearest valid surface.

Reason: I'd really really love to have a vanilla-like mod that does not disable death penalty, is very simple, and keeps my loot safe no matter what, but without feeling like I cheated to get the items back. I feel like this would be ideal for me, if it kept my loot safe. Edit: for now I'm using Corpse mod, after I found about it

**Comment by TBlazeWarriorT** [comment]
I'd like to add another suggestion too, I think it might fit on this issue, maybe
It would also be great to have a toggle if this affects EXP or not. EXP is hardcoded to despawn after 5 minutes and I haven't seen any mod that offer changing this. I've lost the Ender Dragon exp thanks to this recently :(

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
