### ISSUE TITLE
[Villager Names] Lowercase custom names

### ISSUE THREAD

**Issue by Haruspik** [ricksouth/serilum-mc-mods#2066]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.47
Environment: Singleplayer

Mod name: Villager Names
Mod version: 7.0

## **Description**
When **useBothCustomAndDefaultNames** is **false** customs names are always lowercase (when in customnames.txt typed 'Septim' in game villager gets name 'septim').  When it is **true** custom names works normal (villager gets name 'Septim').

I looked code on GitHub and I think that problem is in **Names.getRandomName()**:
as I can see, **randomFromList** returns lowercased name. When **useBothCustomAndDefaultNames** == **true** it returns capitalized name
`return StringFunctions.capitalizeEveryWord(randomFromList(villagerNameList));`
but otherwise it returns without capitalizing
`return randomFromList(customVillagerNames);`

P.S. I don't have experience in Minecraft modding, sorry if I wrote smth silly.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 7.1 of Villager Names. Apologies for any inconvenience. I did indeed return the raw name, and a different function made the custom names lowercase. Good catch ;)

https://curseforge.com/minecraft/mc-mods/villager-names
