### ISSUE TITLE
Village Spawn point not compatible with Terralith

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#2074]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.2.0
Environment: Singleplayer 

Mod name: Village Spawn Point 
Mod version: 1.20.1-4.1

## **Description**
Hey! Crashes every time I create a new world having Terralith Installed, will attach the log.

## **Crash report**

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13537810/latest.log)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! While I couldn't replicate it locally, I've attempted to fix it by checking if the chunk is loaded before finding the surface block position. This should be fixed in version 7.12 of Collective. Village Spawn Point doesn't need an update.

https://curseforge.com/minecraft/mc-mods/collective/files

**Comment by ghost** [comment]
Hi there!
Felt like I have to update this with my latest knowledge, apparently it wasn't a village spawnpoint mod issue per se, it was caused somehow by cyclic. Cyclic has a fix for Terralith as a separate .json which has fixed Village Spawnpoint not working as well in the same evening I posted this issue. I am currently at work and unfortunately cannot provide more info on the matter.
Despite that, thank you for taking the time to update and try and fix what had to do with VillageSpawnPoint, it is a great mod.

Best regards!

**Comment by ricksouth** [comment]
Good to hear! Either way my fix shouldn't influence that in an incompatible kind of way. Appreciate it the kind words :)
