### ISSUE TITLE
advanced config to adjust the drop rate of each ore

### ISSUE THREAD

**Issue by Enno89** [ricksouth/serilum-mc-mods#2078]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge

Mod name: Mineral Chance

## **Feature description**
After testing the mod by simply removing a little mountain beside my house i ended up with around 1.700 Cobblestone, 9 Diamonds, 6 Emeralds, 7 Redstone, 5 Lapislazuli, 9 Gold Nuggets and 7 Iron Nuggets after around 1-1,5 hours.
For me that feels way to off in terms of high quality ores (Diamonds and Emeralds).
So i came up with the following idea:
First the mod determines the chance to drop an ore. Then, instead of picking from all the ores with the same chance, the mod should pick the actual ore with an indivudual set chance.
For Example: The chance for a drop is still around 2%, But then, the dropped ore would have a chance of 5% to be a diamond; 5% for an emerald, 15% for Redstone, 15% for Lapislazuli, 15% for Gold Nuggets, 20% for Iron Nuggets and also in addition to those ores Coal with a chance of 25% to further reduce the amount of high quality ores for balancing.

Of course the chance for the induvidual ores can be changed in the config by players if needed/wanted.
The above mentioned chances are just quick numbers to show it off.

I hope this sounds interessting enough for you to implement it to further balance it for players that not lay one finger on the config.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
