### ISSUE TITLE
Use a tag for isMilkable in Collective

### ISSUE THREAD

**Issue by ryleu** [ricksouth/serilum-mc-mods#2124]
## **Information**
Mod name: Milk All Mobs (and Collective as the code for this would be located there)

## **Feature description**
https://github.com/Serilum/Collective/blob/eb05cec1e8edc1ddfd56b982c8046cd9f6d0c8a7/Common/src/main/java/com/natamus/collective/functions/EntityFunctions.java#L45-L55

I saw these lines and I would prefer using a tag so that it a) is configurable and b) isn't so messy.

That way in a datapack you could just have this:
```json
{
  "values": [
    "some_mod:some_mammal"
  ],
  "replace": false
}
```
To make `some_mammal` from `some_mod` milkable.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
