### ISSUE TITLE
Broadcast first join message

### ISSUE THREAD

**Issue by Crystal-Spider** [ricksouth/serilum-mc-mods#2154]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric

Mod name: First Join Message

## **Feature description**
A configuration option to broadcast the first join message to every connect player so that new players are immediately recognized by everyone.

Maybe it could be nice to make this an addition rather than something exclusive, so there could be a specific player first join message that only the player will see **and** a first join message for everyone to see.  
This would mean to add two new configuration options:  

> **firstJoinMessageBroadcast** (default = ""): The message that will be broadcasted to all players when a new player joins a world for the first time. Possible to include the player's name with $username (or something similar)
  
> **firstJoinMessageBroadcastTextFormattingColourIndex**: same as non broadcast, but for the broadcast message

And you could make it so that an empty message simply disables that message (so that one can choose whether to have only the broadcast, only the specific, or both)

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thank you for opening the feature request and giving the mod a try! This has been added in version 3.4 of First Join Message. Thanks to @xNicklaj for the work.

https://curseforge.com/minecraft/mc-mods/first-join-message
