### ISSUE TITLE
Add translation files to Pumpkillager's Quest

### ISSUE THREAD

**Issue by zc1108aaa** [ricksouth/serilum-mc-mods#2169]
## **Information**
Minecraft version: 1.xx.xx 1.20.1
Modloader: Forge / Fabric FABRIC

Mod name: Mod 1.20.1.3.6

## **Feature description**
I've had this amazing idea!
![2024-01-10_00 08 12](https://github.com/Serilum/.issue-tracker/assets/155424398/ee700797-4245-4ede-a523-fc00898a9886)
![2024-01-10_20 17 13](https://github.com/Serilum/.issue-tracker/assets/155424398/b2f719bb-e81e-40e0-bd7f-917829d5aac3)
![2024-01-11_14 41 03](https://github.com/Serilum/.issue-tracker/assets/155424398/55c11770-f51e-46a9-a5cd-e1c3a2eb415d)

I don't know what to say
![2024-01-08_08 58 26](https://github.com/Serilum/.issue-tracker/assets/155424398/96b7087c-2b09-48a2-9318-a1479de3c311)

**Comment by zc1108aaa** [comment]
don't understand
English

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
