### ISSUE TITLE
respawndelay: prevent players from passing through walls

### ISSUE THREAD

**Issue by Miloxium** [ricksouth/serilum-mc-mods#2176]
## **I, it's just an idea that I have playing with friend and with the respawndelay mod**
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric

Mod name: Mod

## **==boring explanation==: One of my friend abuse a lot off this mod that I use at a compromise between the gamerule keepInventory and the fact that it's overpower, so I use it with the option of respawning were you were in spectate and so we can chose were to spawn. One of them use it to pass through walls and see caves to mine diamonds, he abuse it to much and I does not find any way to spot it in the option menu.

==the idee==: So I think it can be cool if you add an option that block the player to pathing throuth walls like that he can't respawn were he doesen't can acces normaly.

==way to do==: I was thinking to put the player in adventure mod with fly and invisibility but I don't know how to do it. I also know that I am not using this mod to the furst purpose so it's okay if you don't want to.

Sorry to my bad English I am french and not that good ;p **
I've had this amazing idea!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
