### ISSUE TITLE
Save and Load Inventories: instead of saving it in a single folder, save it per player

### ISSUE THREAD

**Issue by JackLiang12** [ricksouth/serilum-mc-mods#2187]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Save and Load Inventories
Mod version: 1.16.5

## **Question**
Hi, I've noticed that this mod has a open GitHub, i was wondering if you guys had a open repository for the 1.16.5 version of the mod that i can fork? Also side question. I was wondering if I can modify the mod for my own modpack, the modification in question is rather than saving it in a single folder, is it possible to save it per player? I.e. if player 1 creates a save inventory it creates a folder with player1's name and save it in the folder, same goes with player 2 so instead of overriding the original save with the same name it would just store them in the player1 and or player2 folder depending on who created it? Is that possible? Thanks!

**Comment by ricksouth** [comment]
At the moment I'm only actively using the Multiloader sources. Appreciate the interest though! It is still available in the Github commit history, after some digging I found it here:

https://github.com/Serilum/.issue-tracker/tree/0d9984f6a30f868fb2d41618ab8e3d96089dfaa4/sources/Save%20and%20Load%20Inventories

Hope that helps!

**Comment by ricksouth** [comment]
I've set it as a feature request for future versions, thank you for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
