### ISSUE TITLE
Overworld piglins default behavior stay the same, but then curable

### ISSUE THREAD

**Issue by allanonmage** [ricksouth/serilum-mc-mods#2204]
## **Information**
Minecraft version: 1.xx.xx
Modloader: Fabric

Mod name: Overworld Piglins

## **Feature description**
I was looking for a mod or datapack to cure piglins and hoglins to keep them in the overworld when I found yours.  I would like to preserve the normal minecraft behavior, but then allow players to cure them the same as a zombie villager.  I love that you usually include config files in your mods, but I haven't installed this one yet, and I don't see a description of the config options for this mod, so if your mode is already capable of this, that's why I missed it.

Can this mod be inverted such that piglins and hoglins are curable, but not not automatically immune to zombification?

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
