### ISSUE TITLE
[Enhancement - Spiders Produce Webs] Make Spiders shoot webs at players that are far away!

### ISSUE THREAD

**Issue by guivnf** [ricksouth/serilum-mc-mods#2215]
## **Information**
Minecraft version: 1.20.1+
Modloader: Forge / Fabric (I'm personally using forge but whatever is ok)

Mod name: [Spiders Produce Webs](https://www.curseforge.com/minecraft/mc-mods/spiders-produce-webs)

## **Feature description**
So in BTW (Better than Wolves), a mod that was recommended by notch himself and was created to furfill and continue the original idea of what minecraft might have been like, they basically made it so spiders can cast a projectile at players, and if that projectile hits the players, it creates a cobweb block on the player's feet, trapping them and making it very hard for players to combat spiders (which let's be honest now, they are kinda weak...), so yeah, my idea is basically having spiders shoot webs at players that go too far away and try to run from combat :)

https://wiki.btwce.com/index.php/Spider

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
