### ISSUE TITLE
Failed to copy the items in the inventory slots defined by other mods.

### ISSUE THREAD

**Issue by Ch3225** [ricksouth/serilum-mc-mods#2219]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.8
Environment: Singleplayer

First mod name: Curios API
First mod version: 5.1.6.1

Second mod name: Cosmetic Armor Reworked
Second mod version: v1a

## **Description**
This starter kit cannot copy the items in the slots defined by these two mods.

**Comment by Ch3225** [comment]
So I am wondering if we can change our code to visit the slots defined by other mods; if not, maybe we can literally talk to other mods' author. I heard that Curios API's slot is dynamitely registered.
Also I have tried several other starter kit mods, the same problem happens when using other mods too. I am a programmer though but I am not an game mod maker that I don't forge api well so it is kinda hard for me and I don't really know the toughness to solving this, I guess this is a pain XD

**Comment by ricksouth** [comment]
It's very difficult to do this in a way that doesn't require a hard dependency. I've recently added a custom starter kit choose screen, which makes it even harder. The solution right now would be to add the items to the inventory itself, and let users equip it.

I'll leave this open as a feature request. Thanks for the interest!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by Ch3225** [comment]
> It's very difficult to do this in a way that doesn't require a hard dependency. I've recently added a custom starter kit choose screen, which makes it even harder. The solution right now would be to add the items to the inventory itself, and let users equip it.
> 
> I'll leave this open as a feature request. Thanks for the interest!

That's seemed to be the best solution at present. I did this in my server. Thank you for your reply. :)
I will check the code and other mod's api to see what I can do with too but I am a noob in coding now XD.
