### ISSUE TITLE
 Configurable Despawn Timer

### ISSUE THREAD

**Issue by Dheamm** [ricksouth/serilum-mc-mods#2223]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Configurable Despawn Timer

## **Feature description**
This mod is very useful, simple and minimalist, it has what is necessary and characterizes many of your mods. However, I think it can be improved, with something that would not only help to maybe save your items, but also to better optimize your world, especially if you have a lot of mods.

I'm new to mods, but I've been playing and configuring servers for a long time and there is a function in "paper'' that allows you to configure the despawn time of a specific item, it is extremely useful if we talk about optimization, for example, I want my items to stay dropped for 20 minutes, but I don't want the rotten flesh, ender pearls from a farm, tree seeds or any item dropped not so useful vanilla or any mod to stay on the ground for 20 minutes.

For this we could make 3 types of despawn, the "general despawn (affects everything, except for the following two despawn)'', the ''player death (all items dropped by a player, the ones dropped when dying and when dropping with the 'Q' and ideally to be able to configure independently both in the category of player death)" and finally a ''filter for a specific item'', compatible with the mods items, of course'. 

It would also be very good to add options to be able to put certain item or certain category of the previous mentioned ''without despawn or infinite ticks'', and another option to show the real human time in ticks, to make it simpler for the general public (1200 ticks = 1 minute).

Example configuration:

- General Despawn = 24000 ticks (20 minutes).

- Player Drop Despawn = Infinite ∞

- Dispawn per object = [
      Rotten meat 1200 ticks (1 minute),
      Ender's Pearl 600 ticks (1 minute),
      Oak Sapling 1200 ticks (1minute),
      Diamonds 48000 ticks (40 minutes),
      Netherite 48000 ticks (40 minutes)].
      
I am sure that these changes are not simple to implement and would take time, but they would certainly make this mod the most complete on this topic, I hope that at least part of these suggestions can be implemented. 

Thanks and best regards.
Anything else you can contact me on discord as: 'dheam.'

PS: Srry for the bible.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️

**Comment by ricksouth** [comment]
Thanks again for the suggestion! This has been added in version 4.0 of Configurable Despawn Timer, alongside some other features :)

https://curseforge.com/minecraft/mc-mods/configurable-despawn-timer/files
