### ISSUE TITLE
When dying to the void, place blocks from the player's inventory instead of just cobblestone

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#2235]
## **Information**
Minecraft version: 1.20.x
Modloader: Forge & Fabric

Mod name: Your Items Are Safe
Mod version: https://github.com/Serilum/Your-Items-Are-Safe/commit/eba90c05214ddf6f0829f3f26e2df89d757ff957

## **Feature description**
In https://github.com/Serilum/Your-Items-Are-Safe/commit/eba90c05214ddf6f0829f3f26e2df89d757ff957#diff-eea2a5115512328b68f1534bcfd94b1a6f1ede8a2c5aa1544a09f59f36d0bbf0R101, you place cobblestone as the platform even if the player does not have cobblestone in their inventory.

Would it be possible for the mod to instead search for full blocks in the player's inventory and place them (consuming the item in the process), instead of placing cobblestone? For example, if a player fell into the void with a chest and 64 iron blocks, 9 blocks of iron would be placed and the resulting chest will contain 55 iron blocks. If a player instead had 4 oak planks, 3 dried kelp blocks, and 2 cobbled deepslate when they fell, those blocks would be placed instead, in an arbitrary pattern.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
