### ISSUE TITLE
Fixed Anvil Repair Cost - New config options

### ISSUE THREAD

**Issue by Silvertide7** [ricksouth/serilum-mc-mods#2246]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge

Mod name: Fixed Anvil Repair Cost

## **Feature description**
It would be really cool if there was a config option that removed the need for materials entirely. This would allow me to give the players an alternative to only going after mending to put on every item. Some items don't even have a repair recipe and can't be repaired at all, but with this config any item with durability could be repaired at the cost of some levels of experience.

Bonus would be if this could be enabled / disabled separately from the anvil repair cost. So if they include a material with it then it will use the levels required for a material repair, and if they don't have the material (or it's a modded item that cant otherwise be repaired) then it will use the xp level requirement set for that case. 

I imagine it as use 5 levels and no material to repair 33% of the durability, or use the material with it and use 1 level. Gives them alternatives to mending. Maybe a tag could be added for items that shouldn't be allowed to be repaired? Lots of suggestions here, take or leave whatever you see fit.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
