### ISSUE TITLE
[Feature Request] [Starter Kit] Starter kits on respawn

### ISSUE THREAD

**Issue by TheGeorginator** [ricksouth/serilum-mc-mods#2311]
Add a config option to grant starter kits on respawn?

I'm making a PVP map, and kits have to be refreshed every time. I can sort-of use "/sk reset", but it cannot be put into a command block, so I can't repeat it. 

I think it would be a cool feature to have, however, I understand if it's not an idea you'd like to continue with.

**Comment by ricksouth** [comment]
Does Save and Load Inventories (https://legacy.curseforge.com/minecraft/mc-mods/save-and-load-inventories) work with what you're trying to do in combination with command blocks? It's not something I've tested it with.

Might be open to adding it as a config to Starter Kit!

**Comment by TheGeorginator** [comment]
I'll test it tonight when I get back home and let you know!

**Comment by TheGeorginator** [comment]
I just tested it, the commands do not work in command blocks unfortunately... 

I know of a vanilla way to do what I need, it's just not easy lol.

But yeah, a config option to grant it on respawn would be very nice! It would also help for apocalypse servers that are very difficult to survive in without items.

Thanks for the fast reply! I really do enjoy all of your mods!

**Comment by ricksouth** [comment]
That's unfortunate. I'll try to get to it in the near future. Thanks for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
