### ISSUE TITLE
More Heads

### ISSUE THREAD

**Issue by Nickstertjefloor** [ricksouth/serilum-mc-mods#2325]
Minecraft version: 1.16.5
Modloader: Forge

Mod name: Just Mob Heads

Hi Serilum (or others),
I love collecting heads in my playthrough, so i searched. Obviously i found this mod and downloaded it. Played a few days, and after a while i started missing heads (From other mods).

Is it possible to add other mods mob-heads myself? And what is the text i need to write? And do i have to be specific like collors?

Thanks,
Nickstertje

p.s.: Here are the mods with heads i'd like to add:
-Ice And Fire
-Quark
-Supplementaries
-Thermal
-Tinkers Construct
-Twilight Forest
-Waddles

**Comment by ricksouth** [comment]
At the moment there isn't currently. I did attempt to add modded data a while ago, but the implementation was rough. It is on my (long) todo list though! I'll set this as a feature request. Appreciate the interest

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
