### ISSUE TITLE
Blaze head all white

### ISSUE THREAD

**Issue by idenher1o** [ricksouth/serilum-mc-mods#2466]
1.20.6 fabric

Blaze heads are all white? 
![image](https://github.com/Serilum/.issue-tracker/assets/173608049/04f69fa4-3ede-43a0-8b83-963b5cbf956a)

**Comment by James103** [comment]
What do you get when you run `/data get entity @s SelectedItem` while holding such a "Blaze Head" in your mainhand?

**Comment by idenher1o** [comment]
![image](https://github.com/Serilum/.issue-tracker/assets/173608049/e3d25ea9-aca1-4190-b273-6e24ba5eddad)

**Comment by LyoGyo** [comment]
A friend of mine is having the same issue, same components as well, when the Blaze head is put on an armour stand or thrown at him he can see the normal texture underneath the white, I think it might be something with the hat layer
Nobody else on my server is having this issue

**Comment by ricksouth** [comment]
Is the issue only with Blaze heads?

**Comment by James103** [comment]
I decoded the base64 in the `texture` field of the player head's data and the URL contained within points to an image where the hat layer is entirely white (instead of transparent). This results in the head appearing all white assuming the hat layer is turned on.

EDIT: I was able to find a replacement skin for the Blaze Head that is the exact same except without an all-white hat layer:
https://github.com/Serilum/Just-Mob-Heads/blob/75dbb99d8442738149cf3a8bcd59c5a62fd029ad/Common/src/main/java/com/natamus/justmobheads/util/HeadData.java#L18
To include it, replace the base64 string near the end of line 18 of HeadData.java in Just Mob Heads with this value:
`eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJmZDg1NzY2OTU1M2JhZjIxZWE4ZWZlNmY5MDNlNzEyYThiOTI3YWZjM2UxNjVjNWNiMGY3NmU0ZjQ5NWY2MiJ9fX0=`

**Comment by ricksouth** [comment]
Awesome, thanks James! Adding it now :)

**Comment by ricksouth** [comment]
This has been fixed in version 8.0 of Just Mob Heads. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files

**Comment by idenher1o** [comment]
Sorry for not answering i was asleep. Thanks for the fix, i love the mod!

**Comment by LyoGyo** [comment]
The same friend as before is have the issue with slime heads now, other player heads with transparency seem to work fine
![image](https://github.com/Serilum/.issue-tracker/assets/81884694/38c61dd6-cf29-4733-a23b-57d97877b0d1)

**Comment by James103** [comment]
> The same friend as before is have the issue with slime heads now, other player heads with transparency seem to work fine

Like the blaze head case, I decoded the base64 in the texture field of the player head's data and the URL contained points to an image where the hat layer is all white instead of transparent.

I was able to find a replacement skin for the Slime Head that is the same except with no all-white hat layer.

https://github.com/Serilum/Just-Mob-Heads/blob/c90d440d8859d4171b149274baeacd7cfced57d2/Common/src/main/java/com/natamus/justmobheads/util/HeadData.java#L99
To include it, replace the base64 near the end of line 99 of HeadData.java in Just Mob Heads with this value (not tested by me):
```
eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRjYjcyYmVjZTZkMzkwMjYyNWY3OWNkNzNhNzlmOTRlZGI2MTMyNmQ1MTBiODAwZTM4ZDJiNDNhZjkxNDhkZSJ9fX0=
```
