### ISSUE TITLE
please update starterkit.

### ISSUE THREAD

**Issue by GoofyRaspberry** [ricksouth/serilum-mc-mods#2470]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.2
Modloader: Forge
Forge version: latest  OR  Fabric loader version: latest
Environment: Singleplayer / Multiplayer

Mod name: Starterkit
Mod version: 5.3

## **Question**
can you please update the 1.18.2 version to 7.0 (latest)? I'm making a modpack and I really want players to be able to choose between multiple starterkits currently, this feature is unavailable for version 5.3.

**Comment by ricksouth** [comment]
While I appreciate the interests, I'm no longer supporting 1.18 unfortunately. I also can't only release a Starter Kit update, since Collective would also need an update. It's just too much work, also because the mod was entirely rewritten for the new choose kit functionality. Apologies for the inconvenience
