### ISSUE TITLE
"No Animal Tempt Delay"...same with Hostile Delay?

### ISSUE THREAD

**Issue by generikb** [ricksouth/serilum-mc-mods#2728]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge

Mod name: No Animal Tempt Delay
Mod version: 1.20.1

## **Question**
Do you think this mod would also "fix" the delay that sometimes happens with mobs attacking a player?  I do a lot of Twitch Integration, and sometimes will spawn in mobs to attack me.  Some of these mobs are normally passive/neutral, but I use the mod CritterFights that I commissioned to give them specific hostility goals.  But I've noticed that sometimes they will stand there and "think" of what their next action is going to be.  Would love it if this somehow fixes that!

**Comment by ricksouth** [comment]
You could give it a try, but I don't think it would. This is specifically for the follow goal when holding food.

A solution for that mod might be to run a task on the tick after they spawn, where a target is set manually instead of waiting for the game to assign it 🤔 But that depends on how it's programmed. It would require an update on their end

**Comment by ricksouth** [comment]
But I can take a look at if it can be done via a hostility delay, just a bit swamped with real life stuff at the moment 😅

**Comment by generikb** [comment]
no worries! It's really not a big deal. Thanks for the response!
