### ISSUE TITLE
[Bug] Baby bees suffocate when touching a block

### ISSUE THREAD

**Issue by Parva-Ovis** [ricksouth/serilum-mc-mods#702]
### Information
**Minecraft version:** 1.16.5
**Forge:** 36.2.0
**Environment:** single player
**Mod:** Realistic Bees 1.16.5-2.2
No other mods installed besides Collective 1.16-2.64

### Description

When bee size is 0.25, baby bees will suffocate when they land on or fly adjacent to a block, which they attempt to do regularly during flight or when following a player with a flower. If the adult bees land when breeding, the spawned baby bee will suffocate to death. The issue goes away if bee size is set to 1.0.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! This has been fixed in version 2.3 of the mod. It seemed like it only happened in the 1.16.5 version. I've added an extra config option (enabled by default) to completely disable suffocation damage for the bees to fix the problem.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files
