### ISSUE TITLE
[Request] option to require entity movement

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ricksouth/serilum-mc-mods#713]
## **Information**
Mod name: Eroding Stone Entities

## **Feature description**
Requiring item entities be moving for their timers to count down could be a nice way of making conversion contraptions slightly more complicated and interesting to engineer. 

As it is now, you can have a water source flow one block onto a hopper setup to sort for the output and that'd be the whole conversion contraption. If entity movement were required, you'd have to do something like make a loop, and you'd therefore have to ensure that items couldn't get caught in places like the inside of a hopper hitbox. 

Even better: a deeper take on this mechanic could also be requiring the item travel a certain distance to convert (implemented by decrementing a counter by the item's speed each tick, instead of simply by 1). This would give players a reason to build long, straight blue ice water streams, or maybe do some trickery with slime block pushing. The point is it opens up a way more possibilities for designs. 

[Also #712 would allow this to be per-'recipe', and players that don't want to mess with this sort of thing would never have to see it.]

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
