### ISSUE TITLE
Extend to allow for items dropped by living entities, similar to Crying Ghasts

### ISSUE THREAD

**Issue by DavGam** [ricksouth/serilum-mc-mods#719]
It makes sense that some items - such as meat - require death.  In other cases, however, it does feel somewhat unnecessary (I dread to imagine how many chickens we've killed for that single feather).  I currently run a mod that causes chickens to occasionally drop feathers, but they're the only animal affected - which feels weird, as Exotic Birds and Alex's Mobs have filled my world with many (apparently featherless) birds.

It would be lovely if the same functionality you used in Crying Ghasts could be made generic and applied to any given mob / item.  Just think of how many lives you'd save <3  Would also allow, say, fertiliser from one mod to occasionally drop from animals from another.  Would be brilliant ~

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
