### ISSUE TITLE
Death Backup - Allow the restore of someone else's inventory

### ISSUE THREAD

**Issue by RobinRMC** [ricksouth/serilum-mc-mods#736]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2855
Environment: Multiplayer

Mod name: Death Backup
Mod version: 1.4

## **Question**
To which inventory gets the back-up restored? To the player executing the command or to the original inventory?

**Comment by ricksouth** [comment]
The backups are from the player using the command. They can see their own death logs and restore from that.

**Comment by RobinRMC** [comment]
But is it possible to allow staff to restore somebody else's inventory?

**Comment by ricksouth** [comment]
It doesn't currently. But I've changed your issue into a feature request. I'll keep you updated here when I get to it. Thanks for giving the mod a try nonetheless!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
