### ISSUE TITLE
[Bug • Double Doors]

### ISSUE THREAD

**Issue by RobinRMC** [ricksouth/serilum-mc-mods#737]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2855
Environment: Multiplayer

Mod name: Double Doors
Mod version: 1.2

## **Description**
The mod requires that the client also has the mod installed, but I saw that you said in another issue that this mod should work if it is only installed on the server.

**Comment by ricksouth** [comment]
It was because Double Doors didn't have an updated 1.12.2 version. I've just released 2.5 for 1.12.2, which has the new features and also allows the mod to just be installed on the server. Thanks for the interest and using the mod!

https://www.curseforge.com/minecraft/mc-mods/double-doors/files/all
