### ISSUE TITLE
[Suggestion] Listing other blocks that count as campfires, and producing other effects from them optionally via configs.

### ISSUE THREAD

**Issue by Darkmega18** [ricksouth/serilum-mc-mods#741]
## **Information**
Mod name: healing campfires

## **Feature description**
I'd like to request the ability to have other campfires be  manually registered in the configs. Such as the different colored campfires from mods such oh the biomes you'll go, or better end forge for example.

Also the ability to specify different combinations of blocks which campfires can be placed on to produce effects in an area. For example placing a soul campfire on glowstone to make mobs in the area glow.

something of a list like:

["minecraft:soul_campfire;minecraft:glowstone;minecraft:glowing-60-0"]
So item id of campfire object, semi-colon, object to be placed on, semi-colon, potion effect to radiate, dash, duration in ticks, dash, amplifier. 

if you want something to apply another effect, you can define the same thing again, but change the effect and that campfire will now radiate two effects. If you miss the second item id and the effects out it will assume to use the base haybale and regeneration effect using the block you defined first.

For example, a regenerating campfire is pretty strong. But I have corail tombstones which has an effect which makes mobs automatically target from immediately which can be placed on the player to make it more risky to do when not in a safe location for example by just defining the normal campfire and haybale combination and adding tombstone:bait with a duration to it.

Alternatively this would open it open to be more than a simple rest point, as the player could definite these as basically radiating zones for effects. Like the soul campfire on glowstone one would be quite good as an early warning system to pick up on people or mobs coming into a defensive perimeter perhaps.

Whether or not you'd be able to force the signalling effect from the campfire or generate other custom effects from the campfire object itself would be up to you however.

aaaaaalternatively, you can open it up to datapacking perhaps, and have people do a json for each object they want to radiate effects and on what block and a radius and stuff. however you want to do it really.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by Darkmega18** [comment]
Well alrighty then. :)

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
