### ISSUE TITLE
Mod Request: Biome Spawn Point

### ISSUE THREAD

**Issue by Tyrius1** [ricksouth/serilum-mc-mods#759]
Hey so I see you have a mod called Village Spawn Point. I was wondering if you could make a mod that set spawn point to a specific biome? I have ideas around setting up biome specific content where biomes are set up in stages of difficulty. Unfortunately the idea is not really possible atm given that i cannot guarantee that a player wont spawn in a dangerous zone.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
