### ISSUE TITLE
All Loot Drops - drop all armour

### ISSUE THREAD

**Issue by PurpleHel** [ricksouth/serilum-mc-mods#766]
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.9
Environment: Singleplayer 
Mod name: Configurable Extra Mob Drops
Does this support dropping all of a mob's inventory? Their armor, or other items (like sophisticated backpacks)? Random things used to do this, but hasn't updated to 1.16. I somehow hadn't seen this mod before, but I noticed it tonight and went 'heeeeeyy, I wonder', but couldn't find an answer in the description on curseforge.

Thanks! You make the best mods, I literally can't play minecraft without your stuff!

**Comment by ricksouth** [comment]
Thanks for the interest and using some of my mods! :)

This mod doesn't have that functionality as it adds extra drops only, but maybe All Loot Drops will work for you?

https://www.curseforge.com/minecraft/mc-mods/all-loot-drops

**Comment by PurpleHel** [comment]
Would all loot include the individual inventory for a given mob, their armor and whatever? I'm not so much interested in like, zombie flesh from zombies, I want the armor they're wearing.

**Comment by ricksouth** [comment]
> Would all loot include the individual inventory for a given mob, their armor and whatever? I'm not so much interested in like, zombie flesh from zombies, I want the armor they're wearing.

At the moment it does not, but I'll have this as a feature suggestion for it. Appreciate it.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
