### ISSUE TITLE
Mods not working on servers

### ISSUE THREAD

**Issue by IzMichael** [ricksouth/serilum-mc-mods#767]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.7
Environment: Multiplayer

Mod name: Death Backup, Double Doors
Mod version: 1.5, 2.4

## **Description**
I'm unable to use either of these mods on my Paper 1.17.1 server, is this a bug / possible?

(Loving the mods! Thanks for the good work!)

**Comment by James103** [comment]
Paper is incompatible with Fabric mods. If you are using Paper in order to optimize your server's performance, consider switching to a Fabric server with the mods [Lithium](https://modrinth.com/mod/lithium), [Starlight](https://modrinth.com/mod/starlight), and possibly [ServerCore](https://modrinth.com/mod/servercore) and/or [Carpet](https://github.com/gnembon/fabric-carpet) (in addition to the mods you listed above).

**Comment by IzMichael** [comment]
I should clarify, I'm using the fabric mods on my Minecraft client, and they work when I play singleplayer, but when I connect to a server, they don't. I'm not installing the mods on the server

**Comment by ricksouth** [comment]
Thanks for the interest in the mods @IzMichael! Both mods mentioned are server-side, so the server needs to have them installed. When playing singleplayer, you're basically simulating a server in the background from your client.

**Comment by IzMichael** [comment]
Aw darn, and I'm assuming there's no way to make the Death Backup mod work client-side?

**Comment by ricksouth** [comment]
Unfortunately not, as it changes the inventory which is server-side. Thanks for the interest though, hope you find a solution that works! :)
