### ISSUE TITLE
Giant Spawn - Custom Texture?

### ISSUE THREAD

**Issue by Red-EyedFairace** [ricksouth/serilum-mc-mods#777]
## **Information**
Mod name: Giant Spawn (Forge)

## **Feature description**
The ability to make Giants use custom textures. (basically make them use separate single texture from zombies?)
-I really want to make them look titans and I dont mind opening a jar and moving and replacing the png there if that's the easiest method to replace them rather than config for it.

**Comment by ricksouth** [comment]
The mod uses the default Giant entity inside the game already. But I might be able to make a mod that can replace textures of entities? Not sure if it's possible. I'll take a look. Thanks for the interest!

**Comment by Red-EyedFairace** [comment]
Oh okay, also got a question, do the giant uses zombie vanilla zombie sounds too? I have a cuztom pack that changes the zombie sounds, it seems like it does not get applied to giant zombies

**Comment by ricksouth** [comment]
They're a separate entity, so you'll need a pack that alters the Giant sound. Think of them as a creeper or skeleton, they're not zombies in the game itself.

**Comment by Red-EyedFairace** [comment]
yeah i know they're different entity but due to the Giant being not on the official release mobs, it doesnt have an entry like "sound/mobs/giant" like zombies does "sounds/mobs/zombies". it seems that giant uses player sounds, so replacing player sound is already a no go. I tried using sound.json and adding like:

```
"entity.giant.hurt": {
	"replace": "true",
    "sounds": [
      "mob/giant/hurt1",
      "mob/giant/hurt2",
	  "mob/giant/hurt3",
	  "mob/giant/hurt4"
    ],
	"subtitles": "subtitles.entity.giant.hurt"
	},
"entity.giant.death": {
	"replace": "true",
    "sounds": [
	"mob/giant/death"	  
    ],
	"subtitles": "subtitles.entity.giant.death"
	},
```

but in the end, they still use presumably player hurt sound :v

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
