### ISSUE TITLE
Idea for new mod

### ISSUE THREAD

**Issue by HARADA-SSV** [ricksouth/serilum-mc-mods#789]
## **Information**
Mod name: Random events for villagers

## **Feature description**
This mod would add random events appearing in the form of text in the chat, e.g. informing that a villager is celebrating his birthday, changed his profession, gave birth to offspring from (name of a villager given from another mod that generates random names for villagers)

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
