### ISSUE TITLE
Request: Certain feature parity with Compass Ribbon mod

### ISSUE THREAD

**Issue by UnIockables** [ricksouth/serilum-mc-mods#830]
## **Information**
Mod name: GUI Compass (Fabric Version)

## **Feature description**
I'm currently using this mod with the [Compass Ribbon](https://www.curseforge.com/minecraft/mc-mods/compass-ribbon) mod. They both already work flawlessly together, but it would be cool if some additional options were available in this mod for customisation to match the features of it.

There are 3 points I wanted to raise with you (a bug, a toggle, and a feature request):

1.  In testing, I noticed a bug: this mod doesn't activate when a compass is in the offhand slot. 

2. I'm using this mod for the coordinates, and the other for the directions, so could there be an option to only display the coordinates? (option in the settings to remove the direction facing letters)

3. In addition to the visibility options that your mod features (to be always visible, or only activate when a compass is in the player's inventory), Compass Ribbon has the option to display when the compass is only on the players hotbar/offhand, or only in the players hand/offhand. Could these options be implemented into yours too?

Thank you for this mod by the way! These issues would be a nice-to-have, rather than a necessity, so no stress if you don't have time to implement them 😊

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
