### ISSUE TITLE
[All Loot Drops] Iron Farm Nerf

### ISSUE THREAD

**Issue by Thiana** [ricksouth/serilum-mc-mods#838]
## **Information**
Minecraft version: 1.18
Modloader: Forge
Forge version: 38.0.16
Environment: Singleplayer

Mod name: All Loot Drops
Mod version: 2.3

## **Description**

The 'All Loot Drops' mod in TVE massively nerfs iron farms. Iron Golems are only dropping a single iron ingot when they die (to a lava blade) instead of the normal 3-5 for Vanilla. 

Thanks.

**Comment by ricksouth** [comment]
Thanks for opening the issue! Apologies this took so long. It has been fixed in version 2.6 of the mod. It adds a new config option, which is enabled by default, so that if the original quantity of the drop was higher that original quanity is kept. Instead of nerfing it.

https://www.curseforge.com/minecraft/mc-mods/all-loot-drops/files
