### ISSUE TITLE
Campfire Spawning In Other Dimensions Is Too Big A Cheat!

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ricksouth/serilum-mc-mods#852]
## **Information**
Mod name: Campfire Spawn and Tweaks

## **Feature description**
I like the Campfire Spawn and Tweaks mod because I like to take a bed with me whenever I'm out exploring so that I can sleep the night away.  This, of course, destroys my base bed spawn, which has forced me to either always build my main base at world spawn, or at least have an outpost there with a quick travel option back to my main base.  This mod could completely fix that entire issue!

However, this mod is just a bit TOO powerful, in my opinion.  After all, vanilla nether respawn anchors exist, and  I think that they should be respected a bit more.  All I ask for is for config options to:

-Disable campfire spawning in any dimension except the Overworld (which already has infinite free respawning with beds, so this really isn't that different or unbalanced).
-Blacklist to disable campfire spawning in specific dimensions (like the nether 😜).
-Require Soul campfire for spawning in the nether.  Or maybe another override list that specifies what fuel the campfire has to be built with to act as a respawn anchor in that dimension instead of the normal campfire.  This would just be a new campfire recipe, not a new campfire (though if you could specify a new flame color, that would be AWESOME).
-Require some form of charging/cost-to-respawn like the vanilla respawn anchor.  Better yet, make it dimentions specific, with config list specifying what fuel that you have to right click the campfire with to 'refuel' it for more respawning in that dimension (perhaps by using some native block to that dimension—sticks, nether bricks, and purpur blocks? Maybe flint for modded dimensions so you don't have to provide a per mod support, though you could include an API to let other mods register a flint alternative).  This 'fuel' item could even be displayed on the normal food cooking spots on the campfire (hey, presto, simple charge count already built in 😜).

I know my "charging campfire spawns" idea would be complicated and costly to implement, but while I do want to make Minecraft more convenient, I don't want it to be so easy it's no longer challenging/fun, and I doubt I'm the only Vanilla Tweaks user who feels that way!  And, so long as you enable the first three disabling config options, the final two "charging campfire spawns" options can wait!

**Comment by 7OOTnegaTerces** [comment]
Having thought about, and used, this mod some more, I've got an improved suggestion to one of my original requests: Instead of just a boolean to disable using campfire spawns in the nether, make a blacklist instead so that users or modpack makers can also disable it in modded dimensions as well!  I've updated my previous comment to reflect this just to keep things simple and avoid missing this alteration.

**Comment by 7OOTnegaTerces** [comment]
Having thought about, and used, this mod some more, I've made improvements to suggestion requests. I've updated my previous comment to reflect this just to keep things simple and avoid confusion or mistakes. Don't worry, now there are **_fewer_** total requests! 😜

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
