### ISSUE TITLE
Some (Minor) Needed Improvements to Infinite Trading...

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ricksouth/serilum-mc-mods#853]
## **Information**
Mod name: Infinite Trading

## **Feature description**
Could we have a few more config options for this mod?  I'd really like to see:

-Disable regular Villager infinite trading (honestly, why isn't it this way, instead of having the option to disable Wandering Traders, when the latter isn't always available and Villager are?  To Be Clear, I don't want to replace the option to disable Wandering Trader infinite trades, I want this option added in addition to that currently existing one).
-Change infinite Villager trades to "Select the number of trades you want", so instead of being forced to choose between the vanilla trade limit and no limit, you can set whatever trade limit you want, with 0 being the vanilla trade limit, and -1 being infinite trades.
-Change infinite Wandering Trader trades to  "Select the number of trades you want" (same as previous).
-Change number of times Villagers reset trades (as an alternative to more trades at once).
-Change number of times Wandering Trader resets trades (rather than zero, the vanilla standard.  Might be more tricky, maybe his llamas count as his job site block?)
-Wandering Trader changes trades on reset (so he doesn't just reset his current trades, but provides all new ones, which would make the previous option all the more valuable and useful).

I guess at this point the mod would need to be renamed from "Infinite Trading" to something else, like "Greatly Improved Trading"!  Though if so, you should definitely include that other idea to allow one to trade all they have of an item with a single click: https://github.com/ricksouth/serilum-mc-mods/issues/571

**Comment by 7OOTnegaTerces** [comment]
So...what do you think?  Do you like this idea?  Will/Might it be implemented some day (specific commitments not required)?!?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
