### ISSUE TITLE
"Naturally Charged Creepers" Should Increase Lightning Strikes On Creepers

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ricksouth/serilum-mc-mods#854]
## **Information**
Mod name: Naturally Charged Creepers

## **Feature description**
While this mod is great for making charged Creepers more common, and even possible underground, I don't feel that the mod truly lives up to it's name, **Naturally** Charged Creepers.  Since the idea of this mod is to "increase the game's difficulty", then why not make it that whenever it rains, there's a chance for a naturally spawning creeper (on the surface) to get hit by lightning, and during thunderstorms most/all naturally spawning creepers get hit!

**Comment by 7OOTnegaTerces** [comment]
So...what do you think?  Do you like this idea?  Will/Might it be implemented some day (specific commitments not required)?!?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
