### ISSUE TITLE
Update sub mods with latest patches and add recently released ones

### ISSUE THREAD

**Issue by PresidentBacons** [ricksouth/serilum-mc-mods#862]
## **Information**
Mod name: The Vanilla Experience (Mod) (Forge)

## **Feature description**
Any chance could you update this for 1.16.5 with the latest patches of all the sub mods, and add some of the more recent ones you have released like Crying Portals and Keep My Soil Tilled?

Would be very much appreciated.

Thanks

**Comment by ricksouth** [comment]
Thanks for the interest! When I first released the TVE mod, I wrote code that combined all mods. That code doesn't work anymore, due to changes in both the mods themselves and Minecraft. There were also some other issues.

I will be attempting another TVE mod update in the near future. When that happens, I'll post another comment on here. For now I'm closing this and focusing on the other bug reports on Github. The mod is not forgotten!
