### ISSUE TITLE
villagers randomly losing the profession behind their name

### ISSUE THREAD

**Issue by wackoamd1** [ricksouth/serilum-mc-mods#872]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 1.12.2
Environment: Multiplayer

Mod name: villager names
Mod version: 3.5

## **Description**
love the mod but when i log in , my villager still have their name but they lose their profession behind their name , picking them up with a golden lasso and putting them down restores the name. and its not that they lose the profession just the tag and pickling up all my villages in my "mall" is not fun 

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
