### ISSUE TITLE
GUI Compass Coordinates Rounding

### ISSUE THREAD

**Issue by MisterMani** [ricksouth/serilum-mc-mods#876]
Minecraft version: 1.12.2
Modloader: Forge 
Forge version: 14.23.5.2860
Environment: Singleplayer 
Mod name: GUI Compass
Mod version: 1.12.2-1.5

I am standing on one block and move a little in any direction (still standing on the same block) and my coordinates change.
At the halfway point on any block, even up and down, my coordinates change.
The cross-section of four blocks is treated as one block, moving in between four blocks doesn't change the coordinates.
Meaning I am not properly being displayed the correct coordinates. 
Is there a reason the coordinates round up at all?

**Comment by ricksouth** [comment]
Unfortunately 1.12 is no longer supported. The mod shows the block position, that's why there's coordinate rounding. I've just released version 2.1 which adresses some desync issues but that's for 1.16+. Sorry for the inconvenience. Thanks for giving the mod a try nonetheless!

https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
