### ISSUE TITLE
Nether Portal Spread / Crying Portals compatibility

### ISSUE THREAD

**Issue by bravely-beep** [ricksouth/serilum-mc-mods#877]
## **Information**
Mod name: Nether Portal Spread

## **Feature description**
It'd be cool to have compatibility with the Crying Portals mod. There could be a setting that prevents the Nether spreading if a certain number of crying obsidian blocks are in the portal's frame. Maybe also have a setting to require the whole frame to be crying obsidian.

**Comment by ricksouth** [comment]
Hey!

I appreciate the suggestion! While I'd love to add all features submitted on the issue-tracker, I've got to prioritize working on them due to having limited time. In order to see which features users would like to see most, I've created https://serilum.com/mods/requests, which shows a table with all feature request submitted.

Users are able to upvote requests by reacting to the first issue comment on **this GitHub page** with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top. You can of course add the reactions yourself too, but don't have to :). The author of the feature is already counted as +1.

I won't only focus on popular features in the upcoming years, but it does help with prioritizing. I'll probably work on a combination of popular and interesting/needed/fun submissions.

I'll close this issue with "not planned" as a way to separate an open feature request from an actual completed issue. This does not actually mean it's not planned! Incompatibilities and bug reports will still remain open.

When the feature is implemented, I'll again post a comment and close it as "completed".

Thank you for taking the time to submit the suggestion! ❤️
