### ISSUE TITLE
Is there any way to add text shadow to the guy compass text?

### ISSUE THREAD

**Issue by aparep7474** [ricksouth/serilum-mc-mods#888]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.10
Environment: Singleplayer 

Mod name: Gui Compass
Mod version: v1.8

## **Question**
Currently in the config file there isn't a way to add text shadow to the gui compass text, and without text shadow it doesn't match some of the other gui elements?

My view:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/64266870/148450802-ec1c5292-a88a-4515-987e-60f4ec5c8d5a.png">
(no text shadow)

EDIT:
I edited the source code to add shadow (change draw to drawShadow) and I rebuilt it for personal use.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
