### ISSUE TITLE
is The Vanilla Experience (the mod) coming to 1.18.1?

### ISSUE THREAD

**Issue by Wedge1453** [ricksouth/serilum-mc-mods#892]
I love it because it saves so much time and helps easily manage modpacks, and encourages having more TVE mods in it.

**Comment by Chuunkyz** [comment]
waiting it too, for 1.18 fabric too plz !

**Comment by WordStormRose** [comment]
In interest of not making a whole new issue for basically the same question: are there plans for porting TVE to 1.18.2? If so, is there an estimate as to when it'll be? Thanks!

**Comment by ricksouth** [comment]
Thanks for the interest! When I first released the TVE mod, I wrote code that combined all mods. That code doesn't work anymore, due to changes in both the mods themselves and Minecraft. There were also some other issues.

I will be attempting another TVE mod update in the near future. When that happens, I'll post another comment on here. For now I'm closing this and focusing on the other bug reports on Github. The mod is not forgotten!
