### ISSUE TITLE
Overlapping areas with the same name should not show enter/leave messages when crossing between them.

### ISSUE THREAD

**Issue by Ithirahad** [ricksouth/serilum-mc-mods#899]
## **Information**
Mod name: Areas

## **Feature description**
Realistically, a lot of areas ingame are not perfect circles, and Areas does not work reliably with huge radii. Enter-leave messages should be suppressed if crossing between areas with identical names.

**Comment by ricksouth** [comment]
This is actually already a feature! If it doesn't work, please open another issue. I've confirmed it working in my dev environment.

From the description:
"You can make areas overlap in order to create different area shapes. The join/leave message will only show when entering for the first time or leaving every overlapping zone."

Thanks for giving the mod a try.
