### ISSUE TITLE
Mob Head Drops from Other Paired Mods

### ISSUE THREAD

**Issue by Anonymun** [ricksouth/serilum-mc-mods#908]
Minecraft version: 1.18.1
Modloader: Fabric
Environment: Multiplayer

Mod name: Just Mob Heads
Mod version: justmobheads-fabric_1.18.x-5.2.jar

## **Question**
I've looked back on the issues in the tab, and seen at least one other asking about this. The server I play in has multiple different mods, and thus bring forth many different mobs to even out the vanilla experience/encounters, enough that normal cows and pigs are less to show (which I personally find fine, the variants are cool af in my opinion even if they're just model differences). When I suggested this to the server owner to be added, I thought this mod was able to pull in not only vanilla heads, but custom heads from the other mods (acolyte, spotted pig, caracal, etc.), so it is a real shame it doesn't do this, and any other possible mob head mods for fabric don't do this either. I was wondering if there's any way this mod would have this feature soon, or in the near future? If it helps, the cross compatibility for the extra heads could be done through a datapack, right?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
