### ISSUE TITLE
Spawn flowers in places where they normally wouldn't

### ISSUE THREAD

**Issue by Bonzai2022** [ricksouth/serilum-mc-mods#934]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.64
Environment: Singleplayer

Mod name: Random Bone Meal Flowers
Mod version: 1.18.1-1.6

## **Description**
The Mod doesn't work in Mushroom Biomes (no other tested).
You can't get any flower through bonemealing gras.
I think it has something to do with the new Biome restrictions.
https://minecraft.fandom.com/wiki/Flower#Natural_generation

**Comment by ricksouth** [comment]
At the moment the mod randomizes flower spawns. So if there are no flowers spawning, which is the case in a mushroom biome, there won't be random flowers either.

I'll leave this open as a feature request, I think a configurable option would be good. Thanks for giving it a try though!

**Comment by Bonzai2022** [comment]
Ah ok.
The mod description is a bit misleading: 
`... a minimalistic mod which randomizes the flowers spawned by bone meal, **_allowing all types to spawn everywhere_**. You won't have to travel thousands of blocks for your automatic flower farm...`

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
