### ISSUE TITLE
[Idea] Allow Portal Frame blocks to take time when mining them + Enderman spawning with Endstone to make it renewable.

### ISSUE THREAD

**Issue by SpiderKolo** [ricksouth/serilum-mc-mods#948]
## **Information**
Mod name: **End Portal Recipe (Fabric)** AND **End Portal Recipe (Forge)**

## **Feature description**
It would be really cool if you could set how long would it take to mine portal frame block.
The fact that you can just instantly pickup blocks makes it so tools don't lose durability. This is not ideal.
Having to mine it for set amount of time would make it much better.

Also - it would be really cool if Enderman were able to spawn while holding Endstone. Perhaps they should be unable to place it in order to prevent them from griefing the world too much.
Even if they spawn with just Endstone in Overworld, it's not like that alone would allow you to craft End Portal Frame as you still need to get the Dragon Egg... but it would allow players to make Enderman farms to gather blocks they could then use for building.

I hope that you will consider adding those ideas into the mod... at least as the settings.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
