### ISSUE TITLE
[New mod suggestion] a "sleeping does not set the weather to sunny"-mod

### ISSUE THREAD

**Issue by Timolino456** [ricksouth/serilum-mc-mods#960]
## **Feature description**
There have been mods like this in the past, but they're either Forge only or do not exist for 1.18.x (and probably will never be updated), so I'll ask you since you are an active modder that has made a lot of smaller mods. :D

The mod would be very simple: sleeping does not change the weather from raining/snowing or stormy to sunny anymore.
**Why?** Because it's unrealistic.

There would be two good ways of implementing this.
1. More simple, a configurable chance of going to sleep changing the weather to sunny, with the default value being 0.
2. How James103 described it on their comment, sleeping advances the weather time as much as it should according to the time skipped by sleeping.

Thanks for your consideration!

**Comment by James103** [comment]
To be "more realistic", sleeping should advance the weather clock by the same amount that it advances the day time. For example, if you sleep and 5 minutes pass on the day time, 5 minutes should also pass on the weather cycle, which may mean one of three things:
* You sleep, during which the weather changes to sunny.
* You sleep, during which the weather doesn't change.
* You sleep, during which it starts raining.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
