### ISSUE TITLE
showDaysPlayedWorld not resetting after death

### ISSUE THREAD

**Issue by smmmadden** [ricksouth/serilum-mc-mods#988]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.1.2
Environment: Multiplayer

Mod name: GUIClock
Mod version: 1.18.1 - 2.3.1

## **Question**
I'm trying to use this setting to record the number of days the played.
	#Show the days played in the world.
	showDaysPlayedWorld = true
Unfortunately, if the player dies and comes back in, the same number of days is shown.  Technically, this makes sense since it would be considered as "cumulative days".  
What I want to record is how many days did the player play before they die.  Then if they did die, the number of days would reset.  This is basically what some users have for Survival Hardcore to keep track of how many days someone played before dying where the goal is 100 days straight.
Is it possible to add another setting like resetDaysPlayedWorldOnDeath to true/false ?
Thanks,
Steve

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
