### ISSUE TITLE
More Sponge Types For Extra Sponges

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ricksouth/serilum-mc-mods#999]
Bigger Sponge Absorption Radius is a very convenient mod in that it allows you to keep all your sponges together in one easy to collect pile, but it doesn't reduce the number of sponges needed (I don't think?!?  Please forgive me if I'm wrong about this!!!).  [Extra Sponges](https://www.curseforge.com/minecraft/mc-mods/extra-sponges) makes sponges upgrade-able so that each individual sponge does absorb more water (as well as adding a Lava sponge!!!), so the ultimate option would be to be able to combine these two effects!

Now, I know you're going to have at least a few problems with this suggestion:
1. This could be very difficult from a technical standpoint, but I don't think it will be!  One simple solution is to just add instead of multiply.  So say a normal sponge provides X absorption radius (which would be Tier 0).  A Tier 1 sponge would have an X+1 (or 2?!?) absorption radius.  Then, your recursive function, rather than just counting sponges and doing the "default sponge radius * neighbouring sponge block count" function at the end, checks the sponge type and adds it's personal absorption radius to a running total that is returned at the of the recursion.  Alternatively you could just only allow sponges of the same type to work together and have a "tiered sponge radius * neighbouring sponge block count" that only counts sponges of the same type as the last one placed, but I don't think that would be any easier, I'd only do it if I felt that was better/more balanced from a game perspective.
2. You're  all about 'vanilla' Minecraft, no new items, just new mechanics.  But this could be a "this mod supports additional sponge types" thing without adding them in this mod!
3. This mod is Forge, that one is Fabric.  This I think is less of an issue since you always provide all your mods in both Forge and Fabric (for which I GREATLY thank you, you're awesome, please do keep it up!!!).  I would ask that you at least make a Forge Extra Sponges (and you might want to make a Fabric one two, depending upon how you do the cross-mod interactions between 'Bigger' and 'Extra', as well as to ensure that there always is a Fabric one, in case the original author is unable to continue for whatever reason).

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
